import {TOOL_LIBRARY} from './missions.js';
const ALLOWED=new Set(['add_role','remove_role','move_role','swap_tool','insert_verifier']);
export function baselineOrganization(mission,memory=[]){
  const seed=mission.domain==='finance_ops'?['document_reader','policy_lookup','human_review','payment_queue']:mission.domain==='support_ops'?['ticket_reader','knowledge_search','human_review','reply_sender']:mission.tools.slice(0,4);
  const roles=seed.filter(t=>mission.tools.includes(t)).map(t=>roleSpec(t));
  for(const lesson of memory){if(lesson.domain===mission.domain&&lesson.tool&&mission.tools.includes(lesson.tool)&&!roles.some(r=>r.tool===lesson.tool))roles.splice(Math.max(1,roles.length-1),0,{name:lesson.roleName||nameFor(lesson.tool),tool:lesson.tool,purpose:lesson.purpose||TOOL_LIBRARY[lesson.tool].purpose,instructions:lesson.instructions||instructionsFor(lesson.tool)});}
  return compile(roles,mission,1,'Baseline synthesized from mission contract, available capabilities, and institutional memory.');
}
export function compile(specs,mission,version,rationale=''){return {id:`org-${mission.id}-v${version}`,version,roles:specs.map((r,i)=>({id:`r${version}-${i}`,name:r.name||nameFor(r.tool),tool:r.tool,purpose:r.purpose||TOOL_LIBRARY[r.tool]?.purpose||'',instructions:r.instructions||instructionsFor(r.tool),model:TOOL_LIBRARY[r.tool]?.model||'tool'})),rationale,createdAt:new Date().toISOString()}}
export function validateSynthesis(mission,p){if(!p||!Array.isArray(p.roles)||p.roles.length<2||p.roles.length>8)return bad('role_count'); const roles=[];for(const r of p.roles){if(!r?.tool||!mission.tools.includes(r.tool)||!TOOL_LIBRARY[r.tool])return bad('invalid_tool');roles.push({name:String(r.name||nameFor(r.tool)).slice(0,56),tool:r.tool,purpose:String(r.purpose||TOOL_LIBRARY[r.tool].purpose).slice(0,180),instructions:String(r.instructions||instructionsFor(r.tool)).slice(0,500)})} return {ok:true,roles,rationale:String(p.rationale||'Model-generated organization').slice(0,400)}}
export function localDiagnosis(mission,run){const fails=run.outcomes.filter(x=>!x.pass), text=fails.map(x=>x.evidence).join(' ').toLowerCase();let tool=null,reason='The evidence does not justify a structural change.'; if(text.includes('duplicate signal=not checked')||text.includes('duplicate signal=null')){tool='cross_case_index';reason='Repeated failures occur across cases because no stage compares the current invoice with previously processed invoices.'} else if(text.includes('total integrity=not checked')||text.includes('total integrity')||text.includes('total_mismatch')){tool='assertion_check';reason='Failed cases show the organization releases work without verifying internal totals against submitted totals.'} else if(text.includes('privacy')||text.includes('unsafe')){tool='redaction';reason='Failed support cases show personal data can reach an external reply without a redaction capability.'} const cap=tool?{name:nameFor(tool),tool,purpose:TOOL_LIBRARY[tool].purpose,instructions:instructionsFor(tool)}:null;return {failureMode:tool?'capability_gap':'local_failure',confidence:tool?.length?0.9:0.55,evidenceIds:fails.map(x=>x.id),reason,neededCapability:cap,source:'local-fallback'}}
export function validateDiagnosis(mission,run,d){const ids=new Set(run.outcomes.filter(x=>!x.pass).map(x=>x.id)); if(!d||!Array.isArray(d.evidenceIds)||!d.evidenceIds.length)return bad('no_evidence'); if(d.evidenceIds.some(x=>!ids.has(x)))return bad('ungrounded_evidence'); const c=Number(d.confidence);if(!Number.isFinite(c)||c<0||c>1)return bad('confidence');const t=d.neededCapability?.tool||d.neededCapability?.preferredTool||null;if(t&&(!mission.tools.includes(t)||!TOOL_LIBRARY[t]))return bad('tool');return {ok:true,diagnosis:{failureMode:String(d.failureMode||'local_failure'),confidence:c,evidenceIds:[...new Set(d.evidenceIds)],reason:String(d.reason||'').slice(0,500),neededCapability:t?{name:String(d.neededCapability.name||nameFor(t)).slice(0,56),tool:t,purpose:String(d.neededCapability.purpose||TOOL_LIBRARY[t].purpose).slice(0,180),instructions:String(d.neededCapability.instructions||instructionsFor(t)).slice(0,500)}:null,source:d.source||'model'}}}
export function governor(mission,run,d){if(run.violations.includes('budget'))return {action:'terminate',reason:'Current organization violates the operating budget.'}; if(!run.outcomes.some(x=>!x.pass))return {action:'continue',reason:'The organization satisfies its operating contract.'}; const rate=1-run.accuracy; if(d.failureMode==='capability_gap'&&d.confidence>=.7&&rate>=.15)return {action:'restructure',reason:`Structural failures affect ${Math.round(rate*100)}% of evaluated work and evidence confidence is ${Math.round(d.confidence*100)}%. The expected benefit justifies organizational change.`}; if(rate<.15)return {action:'retry',reason:'Failure is too isolated to justify organizational change.'}; return {action:'repair',reason:'Failures repeat, but evidence is not strong enough for a full restructure.'}}
export function localMutations(mission,org,d){const out=[];const t=d.neededCapability?.tool;if(t&&!org.roles.some(r=>r.tool===t))out.push({type:'add_role',label:`Add ${d.neededCapability.name}`,evidenceIds:d.evidenceIds,role:d.neededCapability,insertIndex:Math.max(1,org.roles.length-1),rationale:d.reason}); if(mission.tools.includes('assertion_check')&&!org.roles.some(r=>r.tool==='assertion_check'))out.push({type:'insert_verifier',label:'Insert final Outcome Verifier',evidenceIds:d.evidenceIds,role:roleSpec('assertion_check'),insertIndex:org.roles.length,rationale:'Conservative alternative: verify claims before irreversible output.'}); if(mission.tools.includes('risk_scoring')&&!org.roles.some(r=>r.tool==='risk_scoring'))out.push({type:'add_role',label:'Add Risk Scorer',evidenceIds:d.evidenceIds,role:roleSpec('risk_scoring'),insertIndex:Math.max(1,org.roles.length-1),rationale:'Alternative organizational design adds explicit risk triage.'}); return out.slice(0,3)}
export function validateMutation(mission,org,d,m){if(!m||!ALLOWED.has(m.type))return bad('type'); if(!Array.isArray(m.evidenceIds)||!m.evidenceIds.length||m.evidenceIds.some(x=>!d.evidenceIds.includes(x)))return bad('grounding');if(['add_role','insert_verifier'].includes(m.type)){const t=m.role?.tool;if(!t||!mission.tools.includes(t)||!TOOL_LIBRARY[t])return bad('role_tool');if(org.roles.some(r=>r.tool===t))return bad('duplicate_tool')}return {ok:true,mutation:{...m,label:String(m.label||m.type).slice(0,80),rationale:String(m.rationale||'').slice(0,400)}}}
export function applyMutation(mission,org,m,version){const specs=org.roles.map(r=>({name:r.name,tool:r.tool,purpose:r.purpose,instructions:r.instructions})); if(['add_role','insert_verifier'].includes(m.type)){const i=clamp(Number.isInteger(m.insertIndex)?m.insertIndex:specs.length-1,0,specs.length);specs.splice(i,0,{name:m.role.name||nameFor(m.role.tool),tool:m.role.tool,purpose:m.role.purpose,instructions:m.role.instructions})} else if(m.type==='remove_role'){specs.splice(clamp(m.targetIndex||0,0,specs.length-1),1)} else if(m.type==='move_role'){const from=clamp(m.targetIndex||0,0,specs.length-1),to=clamp(m.insertIndex||0,0,specs.length-1);const [r]=specs.splice(from,1);specs.splice(to,0,r)} else if(m.type==='swap_tool'){const i=clamp(m.targetIndex||0,0,specs.length-1);specs[i]=roleSpec(m.role.tool)} return compile(specs,mission,version,m.rationale)}
export function candidateScore(mission,org,run){const hard=run.violations.length===0; const score=run.accuracy*100-run.cost*5-run.latency*.4-org.roles.length*.4;return {hard,score:Math.round(score*100)/100}}
export function selectCandidate(xs){return xs.filter(x=>x.score.hard).sort((a,b)=>b.score.score-a.score.score)[0]||null}
export function diff(a,b){const A=new Set(a.roles.map(r=>r.tool)),B=new Set(b.roles.map(r=>r.tool));return {added:b.roles.filter(r=>!A.has(r.tool)),removed:a.roles.filter(r=>!B.has(r.tool)),reordered:a.roles.map(r=>r.tool).join('>')!==b.roles.map(r=>r.tool).join('>')}}
export function lesson(mission,d,chosen){const t=chosen.mutation.role?.tool||d.neededCapability?.tool;return {id:`lesson-${Date.now()}`,domain:mission.domain,tool:t,roleName:chosen.mutation.role?.name||nameFor(t),purpose:TOOL_LIBRARY[t]?.purpose||'',instructions:chosen.mutation.role?.instructions||instructionsFor(t),evidenceIds:d.evidenceIds,quality:chosen.run.accuracy,cost:chosen.run.cost,createdAt:new Date().toISOString()}}
export function nameFor(t){return ({document_reader:'Invoice Intake',ticket_reader:'Ticket Intake',policy_lookup:'Policy Controller',payment_queue:'Payment Executor',reply_sender:'Reply Executor',human_review:'Human Review Router',cross_case_index:'Cross-case Verifier',redaction:'Privacy Guard',assertion_check:'Outcome Verifier',knowledge_search:'Knowledge Analyst',risk_scoring:'Risk Scorer',schema_validator:'Schema Gate'})[t]||'Specialist'}
export function instructionsFor(t){return ({document_reader:'Normalize the invoice into structured fields. Never approve or reject.',ticket_reader:'Normalize the request. Preserve meaning but do not expose sensitive data downstream unnecessarily.',policy_lookup:'Identify whether policy requires human review. Do not execute an irreversible action.',payment_queue:'Prepare payment only when upstream controls are clear. Never override a rejection or review.',reply_sender:'Prepare external reply only from sanitized, policy-cleared context.',human_review:'Route material exceptions and sensitive cases to a human. Never silently auto-resolve them.',cross_case_index:'Compare the current case with prior processed cases and surface exact matches or likely duplicates.',redaction:'Detect and redact personal or payment data before any external reply.',assertion_check:'Independently verify stated totals and assertions before release.',knowledge_search:'Retrieve the smallest relevant operational knowledge set.',risk_scoring:'Score operational risk from observed signals. Do not manufacture hidden facts.',schema_validator:'Validate required fields before downstream processing.'})[t]||'Perform only the assigned capability and return observable evidence.'}
function roleSpec(t){return {name:nameFor(t),tool:t,purpose:TOOL_LIBRARY[t]?.purpose||'',instructions:instructionsFor(t)}}
function bad(reason){return {ok:false,reason}}
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}
