const LOG_POLL_MS=1500,COMPANY_POLL_EVERY=3,MAX_LOG_ROWS=24;
let lastCompany='',lastSession='',lastTerminalEvent='',inflight=false,tick=0,cachedCompany=null,lastArtifactSignature='',pollFailures=0,refreshQueued=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tm=t=>{try{return new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch{return''}};
const pretty=s=>String(s||'').replaceAll('_',' ');
const sessionFromRecords=r=>r.filter(x=>x.kind==='operating_session').sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))[0]?.id||'';
const scoped=r=>r.filter(x=>!lastSession||!x.data?.sessionId||x.data.sessionId===lastSession);
const roleName=d=>pretty(d.role||d.function||d.name||'Role').replace(/\b\w/g,c=>c.toUpperCase());
const route=d=>[d.provider,d.model].filter(Boolean).join('/')||'runtime';
function lifecycle(type,d={},fallback=''){
 const t=String(type||'').toUpperCase();
 if(t==='ORGANIZATION_ASSEMBLED')return `Organization assembled — ${(d.organization?.functions||[]).map(pretty).join(' → ')}.`;
 if(t==='ROLE_STARTED')return `${roleName(d)} · ${route(d)} → started`;
 if(t==='ROLE_COMPLETED')return `${roleName(d)} · ${route(d)} → completed${d.latencyMs?` · ${(d.latencyMs/1000).toFixed(1)}s`:''}${d.recovered?' · recovered':''}`;
 if(t==='ROLE_ESCALATED')return `${roleName(d)} escalated → ${route(d)}${d.errorCode?` · ${d.errorCode}`:''}`;
 if(t==='ROLE_RECOVERED')return `${roleName(d)} recovered → ${route(d)}`;
 if(t==='ROLE_FAILED')return `${roleName(d)} · ${route(d)} → failed${d.errorCode?` · ${d.errorCode}`:''}`;
 if(t==='ROLE_ARTIFACTS_ASSEMBLED')return `Synthesizer → completed · ${d.fileCount||d.files?.length||0} artifact${(d.fileCount||d.files?.length||0)===1?'':'s'} assembled locally`;
 if(t==='CLAIM_VERIFIER_STARTED')return `Verifier · ${route(d)} → checking claim-level truth`;
 if(t==='CLAIM_VERIFIER_REJECTED')return d.rejected?.length?`Verifier → rejected ${d.rejected.length} unsupported claim${d.rejected.length===1?'':'s'}`:'Verifier → did not approve candidate';
 if(t==='CLAIM_VERIFIER_PASSED')return `Verifier · ${route(d)} → passed`;
 if(t==='CLAIM_VERIFIER_FAILED')return `Verifier → failed closed${d.errorCode?` · ${d.errorCode}`:''}; result is not READY`;
 if(t==='CLAIM_REPAIR_STARTED')return `Repair · ${route(d)} → started`;
 if(t==='CLAIM_REPAIR_COMPLETED')return `Repair · ${route(d)} → completed`;
 if(t==='CLAIM_REPAIR_FAILED'||t==='CLAIM_REPAIR_REJECTED')return 'Repair → failed truth gate; result is not READY';
 if(t==='READY_ELIGIBLE')return 'Truth gate → passed; artifacts are eligible for READY';
 if(t==='FIRST_VALUE_QUEUED')return 'First-value execution queued on the durable worker';
 if(t==='WORK_RECOVERED')return d.message||'Worker recovered interrupted execution';
 if(t==='WORK_TERMINAL_FAILURE')return d.message||'Execution reached a terminal failure state';
 if(t==='RUN_TELEMETRY')return d.message||fallback||'Run telemetry persisted';
 if(t==='ORGANIZATION_NO_ARTIFACTS')return d.message||'Organization produced no publishable artifact';
 if(t==='EVALUATOR_JUDGMENT')return d.reasons?.length?`Evaluator → rejected ${d.reasons.length} contract issue${d.reasons.length===1?'':'s'}`:'Evaluator → mission contract passed';
 if(t==='STRUCTURAL_FAILURE')return 'Evaluator → structural failure; Governor may restructure the organization';
 if(t==='ORGANIZATION_PROMOTED')return d.message||'Governor → promoted a better organization';
 if(t.includes('GOVERNOR')||t.includes('EXPERIMENT')||t.includes('CANDIDATE')||t.includes('FROZEN'))return d.message||fallback||pretty(t);
 return fallback||d.message||pretty(t);
}
function human(evt){const d=evt?.data||{},type=String(d.type||'UPDATE'),p=d.data||{},fallback=String(d.message||p.message||pretty(type));return{id:String(evt.id||`${type}:${d.occurredAt||evt.created_at||Math.random()}`),type,message:lifecycle(type,p,fallback),data:p,at:d.occurredAt||evt.created_at||evt.updated_at}}
function stage(e){const t=String(e?.type||'').toUpperCase();if(!t)return'Working on it';if(t.includes('READY'))return'Result ready';if(t.includes('REPAIR'))return'Repairing claims';if(t.includes('VERIFIER')||t.includes('EVALUATOR')||t.includes('VERIFY'))return'Checking the result';if(t.includes('ROLE_'))return'Running the organization';if(t.includes('PLAN')||t==='ORGANIZATION_ASSEMBLED')return'Planning the work';if(t.includes('RESEARCH')||t.includes('EVIDENCE'))return'Gathering evidence';if(t.includes('GOVERNOR')||t.includes('EXPERIMENT'))return'Testing the organization';if(t.includes('FAIL')||t.includes('DEGRADED'))return'Recovering safely';return'Doing the work'}
function truthState(events){let eligible=false,failed=false;for(const e of events){const t=e.type.toUpperCase();if(t==='READY_ELIGIBLE'||t==='CLAIM_VERIFIER_PASSED')eligible=true;if(['CLAIM_VERIFIER_REJECTED','CLAIM_VERIFIER_FAILED','CLAIM_REPAIR_REJECTED','CLAIM_REPAIR_FAILED'].includes(t))eligible=false;if(t==='RESULT_PARTIAL')failed=true;if(t==='RESULT_READY')failed=false}return{eligible,failed}}
function artifactTruth(records){const artifacts=scoped(records).filter(x=>x.kind==='artifact'&&['ready','partial'].includes(x.state)).sort((a,b)=>String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||'')));const a=artifacts[0];if(!a)return{readiness:null,ready:false,partial:false,artifact:null};const readiness=a.data?.readiness||(a.data?.claimVerification?.passed===true?'READY':'PARTIAL');return{readiness,ready:a.state==='ready'&&readiness==='READY',partial:readiness!=='READY',artifact:a}}
function status(records,events){const r=scoped(records),approval=r.find(x=>x.kind==='approval_request'&&['pending','waiting'].includes(x.state)),access=r.find(x=>x.kind==='capability_access_request'&&x.state==='open'),artifact=artifactTruth(records),last=events.at(-1);if(approval||access)return{label:'Needs you',tone:'warn'};if(artifact.ready)return{label:'Ready',tone:'good'};if(artifact.partial)return{label:'Partial',tone:'warn'};if(last?.type==='WORK_TERMINAL_FAILURE')return{label:'Failed',tone:'warn'};if(pollFailures>1)return{label:'Reconnecting',tone:'warn'};return{label:'Working',tone:'live'}}
function ensureStyles(){if(document.getElementById('cz-live-log-styles'))return;const s=document.createElement('style');s.id='cz-live-log-styles';s.textContent=`.cz-live-log-panel{margin:18px 0 112px;border:1px solid rgba(121,255,57,.16);background:rgba(7,14,8,.82);border-radius:18px;padding:18px 20px;backdrop-filter:blur(12px)}.cz-live-log-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.cz-live-log-head>div{display:flex;flex-direction:column;gap:5px}.cz-live-log-head strong{font-size:14px;color:#eef7eb}.cz-live-pulse{display:inline-flex;align-items:center;gap:7px;font-size:11px;color:#9cff3d;text-transform:uppercase;letter-spacing:.11em}.cz-live-pulse.warn{color:#f3c453}.cz-live-pulse i{width:7px;height:7px;border-radius:50%;background:currentColor}.cz-live-log-list{display:flex;flex-direction:column;max-height:330px;overflow:auto;scrollbar-width:none}.cz-live-log-list::-webkit-scrollbar{display:none}.cz-live-log-row{display:grid;grid-template-columns:72px 12px 1fr;gap:10px;padding:10px 0;border-top:1px solid rgba(255,255,255,.05);opacity:.72}.cz-live-log-row.latest{opacity:1}.cz-live-log-time{font:11px/1.5 ui-monospace,monospace;color:#738174}.cz-live-log-dot{width:7px;height:7px;border-radius:50%;background:#667367;margin-top:5px}.cz-live-log-row.latest .cz-live-log-dot,.cz-live-log-row.good .cz-live-log-dot{background:#9cff3d}.cz-live-log-row.bad .cz-live-log-dot{background:#ff8d72}.cz-live-log-row.governor .cz-live-log-dot{background:#b98cff}.cz-live-log-row strong{display:block;font-size:13px;line-height:1.45;font-weight:550;color:#e5eee2}.cz-live-log-row small{display:block;margin-top:3px;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#69766a}.cz-live-log-empty{padding:12px 0;color:#758076;font-size:13px}@media(max-width:760px){.cz-live-log-panel{margin:14px 0 122px;padding:15px}.cz-live-log-row{grid-template-columns:58px 10px 1fr;gap:8px}}`;document.head.appendChild(s)}
function tone(t=''){t=t.toUpperCase();if(t.includes('PASS')||t==='RESULT_READY'||t==='READY_ELIGIBLE')return'good';if(t.includes('FAIL')||t.includes('REJECT'))return'bad';if(t.includes('GOVERNOR')||t.includes('EXPERIMENT'))return'governor';return''}
function ensurePanel(){ensureStyles();const work=document.querySelector('.premium-work');if(!work)return null;let p=document.querySelector('.cz-live-log-panel');if(p)return p;p=document.createElement('section');p.className='cz-live-log-panel';p.setAttribute('aria-live','polite');p.innerHTML='<div class="cz-live-log-head"><div><span class="eyebrow">LIVE LOG</span><strong>What Company Zero is doing</strong></div><span class="cz-live-pulse"><i></i><b>live</b></span></div><div class="cz-live-log-list"><div class="cz-live-log-empty">Waiting for the first real runtime event…</div></div>';const c=document.querySelector('.composer-wrap');c&&c.parentElement===work?work.insertBefore(p,c):work.appendChild(p);return p}
function mount(events){const p=ensurePanel(),list=p?.querySelector('.cz-live-log-list');if(!list)return;const desired=events.slice(-MAX_LOG_ROWS),near=list.scrollHeight-list.scrollTop-list.clientHeight<56;list.innerHTML=desired.length?desired.map((e,i)=>`<div class="cz-live-log-row ${tone(e.type)} ${i===desired.length-1?'latest':''}"><span class="cz-live-log-time">${esc(tm(e.at))}</span><span class="cz-live-log-dot"></span><div><strong>${esc(e.message)}</strong><small>${esc(pretty(e.type))}</small></div></div>`).join(''):'<div class="cz-live-log-empty">Waiting for the first real runtime event…</div>';if(near)list.scrollTop=list.scrollHeight;const pulse=p.querySelector('.cz-live-pulse');if(pulse){pulse.classList.toggle('warn',pollFailures>1);pulse.querySelector('b').textContent=pollFailures>1?'reconnecting':'live'}}
function patchChrome(company,events){if(!company||!document.querySelector('.premium-work'))return;const r=scoped(company.records||[]),artifactRecords=r.filter(x=>x.kind==='artifact'&&['ready','partial'].includes(x.state)),artifacts=artifactRecords.length,readyArtifacts=artifactRecords.filter(x=>x.state==='ready'&&(x.data?.readiness||(x.data?.claimVerification?.passed===true?'READY':'PARTIAL'))==='READY').length,evidence=r.filter(x=>x.kind==='world_fact'&&x.data?.classification==='EXTERNAL_OBSERVATION').length,truth=artifactTruth(company.records||[]),st=status(company.records||[],events),last=events.at(-1),meta=document.querySelector('.command-meta');if(meta){const spans=meta.querySelectorAll(':scope > span:not(.status-pill)');if(spans[0])spans[0].textContent=`${artifacts} artifact${artifacts===1?'':'s'}`;if(spans[1])spans[1].textContent=`${evidence} receipt${evidence===1?'':'s'}`;const pill=meta.querySelector('.status-pill');if(pill){pill.className=`status-pill ${st.tone}`;pill.innerHTML=`<i></i>${esc(st.label)}`}}const k=document.querySelectorAll('.mission-kpis > div');if(k[0]?.querySelector('strong'))k[0].querySelector('strong').textContent=stage(last);if(k[1]?.querySelector('strong'))k[1].querySelector('strong').textContent=evidence?`${evidence} source receipt${evidence===1?'':'s'}`:'No external evidence';if(k[2]?.querySelector('strong'))k[2].querySelector('strong').textContent=readyArtifacts?`${readyArtifacts} verified ready`:artifacts?`${artifacts} candidate`:'Building V1';const aside=document.querySelector('.aside-head > span:last-child');if(aside)aside.textContent=st.label;const title=document.querySelector('.live-output-head h2');if(title)title.textContent=artifacts?truth.ready?`${artifacts} verified artifact${artifacts===1?'':'s'} ready`:`${artifacts} candidate artifact${artifacts===1?'':'s'} · verification pending`:evidence?`${evidence} source receipt${evidence===1?'':'s'} captured`:'Work will appear here as it becomes real'}
function signature(records=[]){return scoped(records).filter(x=>x.kind==='artifact'&&['ready','partial'].includes(x.state)).map(x=>`${x.id}:${x.data?.deliverableVersion||1}:${x.updated_at||x.created_at||''}`).sort().join('|')}
function refresh(){if(refreshQueued)return;refreshQueued=true;document.getElementById('refresh')?.click();setTimeout(()=>refreshQueued=false,900)}
async function poll(){if(inflight)return;const id=localStorage.cz_active||'';if(!id){lastCompany=lastSession='';cachedCompany=null;return}inflight=true;tick++;try{if(id!==lastCompany){lastCompany=id;lastSession='';cachedCompany=null;lastArtifactSignature=''}const need=!cachedCompany||tick%COMPANY_POLL_EVERY===0||!lastSession,[cr,er]=await Promise.all([need?fetch(`/api/v1/companies/${encodeURIComponent(id)}`,{cache:'no-store'}):Promise.resolve(null),fetch(`/api/v1/companies/${encodeURIComponent(id)}/runtime-events`,{cache:'no-store'})]);if(!er.ok)throw Error('runtime_events');if(cr){if(!cr.ok)throw Error('company');cachedCompany=await cr.json()}if(cachedCompany&&!lastSession)lastSession=sessionFromRecords(cachedCompany.records||[]);const payload=await er.json(),events=(payload.items||[]).filter(x=>!lastSession||x.data?.sessionId===lastSession).sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))).map(human);pollFailures=0;mount(events);patchChrome(cachedCompany,events);if(cachedCompany){const sig=signature(cachedCompany.records||[]);if(lastArtifactSignature&&sig!==lastArtifactSignature)refresh();lastArtifactSignature=sig}const terminal=events.at(-1);if(terminal&&['RESULT_READY','RESULT_PARTIAL','ORGANIZATION_PROMOTED'].includes(terminal.type)&&terminal.id!==lastTerminalEvent){lastTerminalEvent=terminal.id;refresh()}}catch{pollFailures++;mount([])}finally{inflight=false}}
setInterval(poll,LOG_POLL_MS);window.addEventListener('hashchange',()=>setTimeout(poll,30));window.addEventListener('storage',poll);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});poll();
