import {FINANCE,SUPPORT,withDrift,publicMission} from './missions.js';
import {executeReferenceWorkload} from './lib/runtime-core.mjs';
import {baselineOrganization,compile,validateSynthesis,localDiagnosis,validateDiagnosis,governor,localMutations,validateMutation,applyMutation,candidateScore,selectCandidate,diff,lesson} from './engine.js';

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let mission=structuredClone(FINANCE); let state=resetState(); let memory=load('cz_memory',[]); let aoEvidence=load('cz_ao',{sessions:[],dashboardShot:null,notes:''});
function resetState(){return {org:null,before:null,after:null,diagnosis:null,decision:null,candidates:[],chosen:null,events:[],brain:{synthesis:'pending',diagnosis:'pending',mutation:'pending'},runtime:'reference',drifted:false,selectedTrace:null}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))} function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function log(title,body,type='normal'){state.events.push({at:new Date().toLocaleTimeString(),title,body,type});renderTimeline()}
async function brain(action,payload){const c=new AbortController();const t=setTimeout(()=>c.abort(),18000);try{const r=await fetch('/api/brain',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload}),signal:c.signal});if(!r.ok)throw new Error(`http_${r.status}`);const d=await r.json();if(!d.ok)throw new Error(d.error||'brain');return d}finally{clearTimeout(t)}}
async function execute(org){try{const r=await fetch('/api/runtime',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mission,org,mode:$('#liveToggle').checked?'live':'reference'})});if(!r.ok)throw new Error(`runtime_${r.status}`);const d=await r.json();if(!d.ok)throw new Error(d.error||'runtime');state.runtime=d.run.mode||d.provider;return d.run}catch(e){state.runtime='browser-reference';log('Runtime fallback',`Server runtime unavailable (${e.message}). Running the same inspectable reference engine in-browser.`,'warn');return executeReferenceWorkload(mission,org)}}
async function observeRun(run){try{const r=await fetch('/api/observe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mission,org:state.org,run,diagnosis:state.diagnosis,decision:state.decision,candidates:state.candidates})});if(!r.ok)return;const d=await r.json();if(d.ok&&d.result?.trace_id)log('Neatlogs trace emitted',`Trace ${d.result.trace_id} · ${d.result.spans||'multiple'} spans.`,'success')}catch{}}
async function synthesize(){try{const r=await brain('synthesize',{mission:publicMission(mission),availableTools:mission.tools,memory:memory.slice(0,8)});const v=validateSynthesis(mission,r.result);if(!v.ok)throw new Error(v.reason);state.brain.synthesis=`TensorMux · ${r.model} · ${r.latencyMs}ms`;return compile(v.roles,mission,1,v.rationale)}catch(e){state.brain.synthesis='local bounded synthesis';log('Brain fallback',`Synthesis provider unavailable or invalid: ${e.message}.`,'warn');return baselineOrganization(mission,memory)}}
async function diagnose(run){try{const r=await brain('diagnose',{mission:publicMission(mission),org:state.org,failures:run.outcomes.filter(x=>!x.pass),traces:run.traces.filter(x=>!x.pass),availableTools:mission.tools});const v=validateDiagnosis(mission,run,{...r.result,source:`TensorMux · ${r.model}`});if(!v.ok)throw new Error(v.reason);state.brain.diagnosis=`TensorMux · ${r.model} · ${r.latencyMs}ms`;return v.diagnosis}catch(e){state.brain.diagnosis='local evidence diagnosis';const d=localDiagnosis(mission,run);const v=validateDiagnosis(mission,run,d);if(!v.ok)throw new Error(v.reason);log('Diagnosis fallback',`Provider unavailable or rejected: ${e.message}.`,'warn');return v.diagnosis}}
async function mutations(){let proposals=[];try{const r=await brain('propose',{mission:publicMission(mission),org:state.org,diagnosis:state.diagnosis,availableTools:mission.tools});proposals=r.result?.mutations||[];state.brain.mutation=`TensorMux · ${r.model} · ${r.latencyMs}ms`}catch(e){state.brain.mutation='local bounded proposals';log('Mutation fallback',`Provider unavailable: ${e.message}.`,'warn');proposals=localMutations(mission,state.org,state.diagnosis)}const out=[];for(const m of proposals){const v=validateMutation(mission,state.org,state.diagnosis,m);if(v.ok)out.push(v.mutation);else log('Proposal rejected',`${m.label||m.type||'mutation'} failed validator: ${v.reason}.`,'reject')}if(!out.length){for(const m of localMutations(mission,state.org,state.diagnosis)){const v=validateMutation(mission,state.org,state.diagnosis,m);if(v.ok)out.push(v.mutation)}}return out.slice(0,3)}
async function evaluateCandidates(ms){const out=[];for(let i=0;i<ms.length;i++){const org=applyMutation(mission,state.org,ms[i],state.org.version+i+1);const run=await execute(org);out.push({mutation:ms[i],org,run,score:candidateScore(mission,org,run)});log(ms[i].label,`${Math.round(run.accuracy*100)}% · $${run.cost.toFixed(2)} · ${run.latency.toFixed(2)}s · ${run.violations.length?'REJECT '+run.violations.join(', '):'CONSTITUTION PASS'}`,run.violations.length?'reject':'candidate')}return out}
async function operate({preserveOrg=false}={}){disable(true);if(!preserveOrg){state=resetState();renderAll();log('Mission accepted',`${mission.title}. Quality ≥${Math.round(mission.qualityFloor*100)}%, budget ≤$${mission.budget.toFixed(2)}, latency ≤${mission.latencyCap}s.`,'change');state.org=await synthesize();log('Organization compiled',`${state.org.roles.length} specialized roles. ${state.brain.synthesis}.`,'change')}else log('Existing company challenged','Operating conditions changed. The organization is preserved; no reset is allowed.','change');renderAll();
try{state.before=await execute(state.org);log('Evaluation completed',`${state.before.passed}/${state.before.total} correct · $${state.before.cost.toFixed(2)} · ${state.before.latency.toFixed(2)}s.`,state.before.violations.length?'fail':'success');state.diagnosis=await diagnose(state.before);log('Evidence diagnosed',`${state.diagnosis.reason} Evidence: ${state.diagnosis.evidenceIds.join(', ')||'none'}.`,state.diagnosis.evidenceIds.length?'fail':'success');state.decision=governor(mission,state.before,state.diagnosis);log(`Governor: ${state.decision.action.toUpperCase()}`,state.decision.reason,state.decision.action==='restructure'?'change':'normal');
if(['restructure','repair'].includes(state.decision.action)){const ms=await mutations();state.candidates=await evaluateCandidates(ms);state.chosen=selectCandidate(state.candidates);if(state.chosen){const old=state.org;state.org=state.chosen.org;state.after=state.chosen.run;const d=diff(old,state.org);log('Organization promoted',`${d.added.map(x=>x.name).join(', ')||'structural change'} promoted only after same-workload proof. ${Math.round(state.before.accuracy*100)}% → ${Math.round(state.after.accuracy*100)}%.`,'success');memory.unshift(lesson(mission,state.diagnosis,state.chosen));memory=memory.slice(0,20);save('cz_memory',memory)}else{state.after=state.before;log('No candidate promoted','Every candidate violated the constitution. The company refuses to claim improvement.','reject')}}else state.after=state.before;renderAll();await observeRun(state.after||state.before)}catch(e){log('Execution stopped',e.message,'reject');renderAll()}finally{disable(false)}}
function disable(v){$('#runBtn').disabled=v;$('#driftBtn').disabled=v||mission.domain!=='finance_ops'||!state.org;$('#runBtn').textContent=v?'Operating…':'Run company'}
function switchMission(id){mission=structuredClone(id==='support'?SUPPORT:FINANCE);state=resetState();renderAll()}
function injectDrift(){if(!state.org||mission.domain!=='finance_ops')return;mission=withDrift(mission);state.drifted=true;operate({preserveOrg:true})}
function renderAll(){renderContract();renderOrg();renderMetrics();renderDiagnosis();renderCandidates();renderEvidence();renderTimeline();renderMemory();renderAO();renderStatus();renderBenchmark()}
function renderContract(){$('#missionTitle').textContent=mission.title;$('#missionDomain').textContent=mission.domain;$('#budget').textContent=`$${mission.budget.toFixed(2)}`;$('#qualityFloor').textContent=`${Math.round(mission.qualityFloor*100)}%`;$('#latencyCap').textContent=`${mission.latencyCap}s`;$('#caseCount').textContent=mission.workload.length;$('#toolCount').textContent=mission.tools.length;$('#driftBadge').hidden=!state.drifted}
function renderOrg(){const root=$('#orgCanvas');if(!state.org){root.innerHTML='<div class="empty">Run the company. Company Zero will compile the smallest organization it believes can satisfy this mission.</div>';return}root.innerHTML=`<div class="org-line">${state.org.roles.map((r,i)=>`<button class="role" data-role="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(r.name)}</strong><small>${esc(r.tool)}</small><em>${esc(r.purpose)}</em></button>`).join('<i>→</i>')}</div><div class="rationale">${esc(state.org.rationale)}</div>`;root.querySelectorAll('.role').forEach(b=>b.onclick=()=>{const r=state.org.roles[+b.dataset.role];openDrawer(r.name,`<p>${esc(r.purpose)}</p><h4>Instructions</h4><pre>${esc(r.instructions)}</pre><h4>Executable capability</h4><pre>${esc(JSON.stringify({tool:r.tool,model:r.model},null,2))}</pre>`)})}
function renderMetrics(){const before=state.before,after=state.after||state.before;$('#accuracy').textContent=after?`${Math.round(after.accuracy*100)}%`:'—';$('#cost').textContent=after?`$${after.cost.toFixed(2)}`:'—';$('#latency').textContent=after?`${after.latency.toFixed(2)}s`:'—';$('#delta').textContent=before&&after&&after!==before?`${Math.round(before.accuracy*100)} → ${Math.round(after.accuracy*100)}`:'No comparison yet';$('#contractState').textContent=after?(after.violations.length?'FAIL '+after.violations.join(', '):'PASS'):'WAITING'}
function renderDiagnosis(){const d=state.diagnosis;$('#decision').textContent=state.decision?.action?.toUpperCase()||'WAITING';$('#decisionReason').textContent=state.decision?.reason||'The Governor waits for execution evidence.';$('#diagnosisBox').innerHTML=d?`<strong>${esc(d.failureMode)}</strong><p>${esc(d.reason)}</p><small>${Math.round(d.confidence*100)}% confidence · ${esc(d.source)} · ${d.evidenceIds.join(', ')}</small>`:'<span class="muted">No diagnosis yet.</span>'}
function renderCandidates(){const root=$('#candidateList');if(!state.candidates.length){root.innerHTML='<div class="empty compact">No candidate organizations yet.</div>';return}root.innerHTML=state.candidates.map((c,i)=>`<button class="candidate ${state.chosen===c?'chosen':''}" data-i="${i}"><div><strong>${esc(c.mutation.label)}</strong><small>${esc(c.mutation.type)} · ${c.org.roles.length} roles</small></div><div class="candidate-metrics"><b>${Math.round(c.run.accuracy*100)}%</b><span>$${c.run.cost.toFixed(2)}</span><span>${c.score.hard?'PASS':'REJECT'}</span></div></button>`).join('');root.querySelectorAll('.candidate').forEach(b=>b.onclick=()=>{const c=state.candidates[+b.dataset.i];openDrawer(c.mutation.label,`<h4>Rationale</h4><p>${esc(c.mutation.rationale)}</p><h4>Constitution</h4><pre>${esc(JSON.stringify({score:c.score,violations:c.run.violations},null,2))}</pre><h4>Organization</h4><pre>${esc(JSON.stringify(c.org.roles.map(r=>({name:r.name,tool:r.tool})),null,2))}</pre>`)})}
function renderEvidence(){const run=state.after||state.before;const root=$('#evidenceRows');if(!run){root.innerHTML='<div class="empty compact">Run a mission to produce evidence.</div>';return}root.innerHTML=run.outcomes.map(o=>`<button class="evidence-row ${o.pass?'pass':'fail'}" data-id="${o.id}"><span>${o.id}</span><b>${o.actual}</b><em>${o.pass?'PASS':'FAIL'}</em><small>${esc(o.evidence)}</small></button>`).join('');root.querySelectorAll('.evidence-row').forEach(b=>b.onclick=()=>{const t=run.traces.find(x=>x.item===b.dataset.id);openDrawer(`${b.dataset.id} execution trace`,traceHTML(t,run.modelAudits?.find(x=>x.item===b.dataset.id)))})}
function traceHTML(t,a){return `<div class="trace">${t.stages.map((s,i)=>`<div class="trace-stage"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(s.role)}</strong><small>${esc(s.tool)} · $${s.cost.toFixed(2)} · ${s.latency.toFixed(2)}s</small><pre>${esc(JSON.stringify(s.output,null,2))}</pre></div></div>`).join('')}<h4>Final</h4><pre>${esc(JSON.stringify({result:t.result,pass:t.pass,provider:t.provider},null,2))}</pre>${a?`<h4>TensorMux audit</h4><pre>${esc(JSON.stringify(a,null,2))}</pre>`:''}</div>`}
function renderTimeline(){const r=$('#timeline');r.innerHTML=state.events.length?state.events.slice().reverse().map(e=>`<div class="event ${e.type}"><span>${e.at}</span><div><strong>${esc(e.title)}</strong><p>${esc(e.body)}</p></div></div>`).join(''):'<div class="empty compact">No operating events yet.</div>'}
function renderMemory(){const r=$('#memoryList');r.innerHTML=memory.length?memory.map(m=>`<article class="memory"><span>${esc(m.domain)}</span><strong>${esc(m.roleName)}</strong><p>${esc(m.purpose)}</p><small>${Math.round((m.quality||0)*100)}% after promotion · evidence ${m.evidenceIds?.join(', ')||'—'}</small></article>`).join(''):'<div class="empty">No institutional memory yet. Successful structural changes become reusable lessons.</div>'}
function renderAO(){const count=aoEvidence.sessions?.length||0;$('#aoCount').textContent=count;$('#aoState').textContent=count?'EVIDENCE LOADED':'NOT YET PROVEN';$('#aoSessionList').innerHTML=count?aoEvidence.sessions.map((s,i)=>`<article class="ao-session"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(s.name||s.title||'AO session')}</strong><p>${esc(s.purpose||s.summary||'')}</p><small>${esc(s.id||s.sessionId||'')}</small></div></article>`).join(''):'<div class="empty compact">Import real AO session evidence. Company Zero never fabricates AO usage.</div>'}
async function renderBenchmark(){try{const r=await fetch('reports/benchmark-report.json',{cache:'no-store'});if(!r.ok)throw new Error('report');const d=await r.json();const f=d.suites.find(x=>x.id==='bench-finance'),u=d.suites.find(x=>x.id==='bench-support');if(f)$('#benchFinance').textContent=`${Math.round(f.before.accuracy*100)} → ${Math.round((f.chosen?.accuracy||f.before.accuracy)*100)}%`;if(u)$('#benchSupport').textContent=`${Math.round(u.before.accuracy*100)} → ${Math.round((u.chosen?.accuracy||u.before.accuracy)*100)}%`;$('#benchmarkRows').innerHTML=d.suites.map(x=>`<article class="benchmark-row"><div><strong>${esc(x.id)}</strong><small>${x.cases} held-out cases</small></div><div><span>BASELINE</span><b>${Math.round(x.before.accuracy*100)}%</b></div><div><span>PROMOTED</span><b>${Math.round((x.chosen?.accuracy||x.before.accuracy)*100)}%</b></div><div><span>CHANGE</span><b>${esc(x.chosen?.label||'none')}</b></div></article>`).join('')}catch{$('#benchmarkRows').innerHTML='<div class="empty compact">Benchmark report unavailable in this preview. Run npm run benchmark.</div>'}}
function renderStatus(){fetch('/api/health').then(r=>r.json()).then(d=>{$('#providerState').textContent=d.tensormuxConfigured?'TensorMux configured':'Reference runtime';$('#providerDot').classList.toggle('live',d.tensormuxConfigured)}).catch(()=>{$('#providerState').textContent='Static preview';$('#providerDot').classList.remove('live')});$('#brainState').textContent=`S ${state.brain.synthesis} · D ${state.brain.diagnosis} · M ${state.brain.mutation}`}

function importMission(file){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);validateMissionInput(d);mission=d;state=resetState();$('#missionSelect').value='';renderAll();log('External mission loaded',`${mission.title}. ${mission.workload.length} cases · ${mission.tools.length} available tools.`,'change')}catch(e){alert(`Invalid mission: ${e.message}`)}};reader.readAsText(file)}
function validateMissionInput(m){if(!m||!['finance_ops','support_ops'].includes(m.domain))throw new Error('domain must be finance_ops or support_ops');if(!m.title||!Array.isArray(m.workload)||m.workload.length<1)throw new Error('title and workload are required');if(!Array.isArray(m.tools)||m.tools.length<2)throw new Error('at least two tools are required');if(!Number.isFinite(Number(m.budget))||!Number.isFinite(Number(m.qualityFloor))||!Number.isFinite(Number(m.latencyCap)))throw new Error('budget, qualityFloor and latencyCap must be numeric');for(const x of m.workload)if(!x.id||!x.expected)throw new Error('every case needs id and expected');m.budget=Number(m.budget);m.qualityFloor=Number(m.qualityFloor);m.latencyCap=Number(m.latencyCap);m.constraints=Array.isArray(m.constraints)?m.constraints:[];m.id=m.id||`imported-${Date.now()}`}

function exportEvidence(){const payload={generatedAt:new Date().toISOString(),mission,organization:state.org,before:state.before,after:state.after,diagnosis:state.diagnosis,decision:state.decision,candidates:state.candidates.map(c=>({mutation:c.mutation,organization:c.org,metrics:{accuracy:c.run.accuracy,cost:c.run.cost,latency:c.run.latency,violations:c.run.violations},score:c.score})),memory,aoEvidence,brain:state.brain,runtime:state.runtime};download('company-zero-evidence.json',JSON.stringify(payload,null,2))}
function importAO(file){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);const sessions=Array.isArray(d)?d:d.sessions;if(!Array.isArray(sessions))throw new Error('Expected sessions array');aoEvidence={...d,sessions};save('cz_ao',aoEvidence);renderAO();log('AO evidence imported',`${sessions.length} real AO sessions loaded for submission evidence.`,'success')}catch(e){alert(`Could not import AO evidence: ${e.message}`)}};reader.readAsText(file)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openDrawer(title,html){$('#drawerTitle').textContent=title;$('#drawerBody').innerHTML=html;$('#drawer').classList.add('open')}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

$('#runBtn').onclick=()=>operate(); $('#driftBtn').onclick=injectDrift; $('#missionSelect').onchange=e=>e.target.value&&switchMission(e.target.value); $('#missionImport').onchange=e=>e.target.files[0]&&importMission(e.target.files[0]); $('#exportBtn').onclick=exportEvidence; $('#drawerClose').onclick=()=>$('#drawer').classList.remove('open'); $('#aoImport').onchange=e=>e.target.files[0]&&importAO(e.target.files[0]);
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${b.dataset.view}`).classList.add('active')});
renderAll();
