
import{ENVIRONMENTS,CAPABILITIES,seed,experiment,promote,rollback}from"./platform/kernel.mjs";
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let page="command",company=load("support");function load(id){try{return JSON.parse(localStorage.getItem("cz5:"+id))||seed(id)}catch{return seed(id)}}function save(){localStorage.setItem("cz5:"+company.environment,JSON.stringify(company))}
const menu=$("#menu");menu.innerHTML=Object.entries(ENVIRONMENTS).map(([id,e])=>`<button data-env="${id}">${e.mark} · ${e.name}</button>`).join("");$("#switch").onclick=()=>menu.classList.toggle("hidden");menu.onclick=e=>{let b=e.target.closest("[data-env]");if(!b)return;company=load(b.dataset.env);menu.classList.add("hidden");render()};
document.querySelector("nav").onclick=e=>{let b=e.target.closest("[data-p]");if(!b)return;page=b.dataset.p;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("on",x===b));renderPage()};
const pct=x=>(x*100).toFixed(1)+"%", head=(k,t,p,a="")=>`<div class="head"><div><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></div>${a}</div>`;
function metrics(){let e=ENVIRONMENTS[company.environment];return`<div class="metrics"><div class="metric"><small>OUTCOME QUALITY</small><b class="${company.quality>=e.floor?'good':'bad'}">${pct(company.quality)}</b><span>contract ≥ ${pct(e.floor)}</span></div><div class="metric"><small>DAILY SPEND</small><b>$${company.cost.toFixed(2)}</b><span>ceiling $${e.budget}</span></div><div class="metric"><small>P95 LATENCY</small><b>${company.latency}m</b><span>ceiling ${e.latency}m</span></div><div class="metric"><small>ORGANIZATION</small><b>v${company.version}</b><span>${company.roles.length} active roles</span></div></div>`}
function flow(roles=company.roles){return`<div class="flow">${roles.map((r,i)=>`${i?'<span class="arrow">→</span>':''}<div class="role"><small>ROLE ${i+1}</small><b>${esc(r.name)}</b><code>${esc(r.capability)}</code></div>`).join("")}</div>`}
function command(){let i=company.incident;return head("OPERATING SYSTEM","Command center",company.outcome,`<button class="btn secondary" id="change">Change company</button>`)+metrics()+`<div class="incident"><i>${i.needed?'!':'✓'}</i><div><b>${esc(i.title)}</b><p>${esc(i.detail)}</p></div>${i.needed?'<button class="btn primary" id="investigate">Open experiment</button>':''}</div><div class="grid"><section class="panel"><div class="ph"><h3>Current organization</h3><small>PRODUCTION · v${company.version}</small></div>${flow()}</section><section class="panel rows"><div class="ph"><h3>Recent work</h3><small>LIVE OPERATIONS</small></div>${company.work.slice(0,7).map(row).join("")}</section></div>`}
function row(w){return`<div class="row"><code>${w.id}</code><b>${esc(w.title)}</b><span>${w.risk}</span><span>${w.duration}m</span><span class="status ${w.status}">${w.status}</span></div>`}
function work(){return head("OPERATIONS","Work","Every job is attached to the organization revision that handled it, with risk, latency and status retained as evidence.")+metrics()+`<section class="panel rows"><div class="ph"><h3>Operating ledger</h3><small>${company.work.length} JOBS</small></div>${company.work.map(row).join("")}</section>`}
function org(){let e=ENVIRONMENTS[company.environment];return head("ORGANIZATION","Production structure",`Version ${company.version} is the promoted executable organization. Roles are capability assignments, not decorative personas.`,company.history.length?'<button class="btn secondary" id="rollback">Rollback</button>':'')+metrics()+`<section class="panel"><div class="ph"><h3>Organization v${company.version}</h3><small>PROMOTED</small></div>${flow()}</section><section class="panel" style="margin-top:18px"><div class="ph"><h3>Operating constitution</h3><small>HARD BOUNDS</small></div><div class="control"><div><b>Outcome</b><p>${esc(company.outcome)}</p></div></div><div class="control"><div><b>Quality floor</b><p>Authoritative evaluation target.</p></div><code>${pct(e.floor)}</code></div><div class="control"><div><b>Daily budget</b><p>Models, tools and review.</p></div><code>$${e.budget}</code></div></section>`}
function experiments(){let x=company.experiment;if(!x)return head("STRUCTURAL SEARCH","Experiments","When operating evidence indicates structural weakness, Company Zero creates challenger organizations and proves them before production.",'<button class="btn primary" id="newexp">Create challenger</button>')+`<section class="panel"><div class="empty">No active experiment. Production v${company.version} continues operating.</div></section>`;return head("SHADOW EVALUATION",`${x.id} · challenger ready`,"Same workload. Independent metrics. Hard promotion gates. The organization brain cannot award itself a win.",'<button class="btn primary" id="promote">Promote challenger</button>')+`<section class="panel"><div class="compare"><div class="candidate"><label>INCUMBENT · v${company.version}</label><h3>Production</h3><dl><dt>Quality</dt><dd>${pct(x.incumbent.quality)}</dd><dt>Daily cost</dt><dd>$${x.incumbent.cost}</dd><dt>P95 latency</dt><dd>${x.incumbent.latency}m</dd><dt>Violations</dt><dd class="bad">${x.incumbent.violations}</dd></dl></div><div class="vs">VS</div><div class="candidate new"><label>CHALLENGER · SHADOW</label><h3>Restructured</h3><dl><dt>Quality</dt><dd class="good">${pct(x.challenger.quality)}</dd><dt>Daily cost</dt><dd class="good">$${x.challenger.cost}</dd><dt>P95 latency</dt><dd>${x.challenger.latency}m</dd><dt>Violations</dt><dd class="good">0</dd></dl></div></div><div class="gate">✓ GATE PASSED · ${x.challenger.cases} shadow cases · +${((x.challenger.quality-x.incumbent.quality)*100).toFixed(1)}pp quality · $${(x.incumbent.cost-x.challenger.cost).toFixed(2)}/day lower cost</div><div class="ph"><h3>Challenger structure</h3><small>ADDS ${x.needed}</small></div>${flow(x.roles)}</section>`}
function caps(){let allowed=new Set(company.capabilities);return head("CAPABILITY REGISTRY","Capabilities","Typed capabilities are the boundary between Company Zero and the outside world. Different companies expose different tools; the organization engine stays unchanged.",'<button class="btn secondary" id="register">+ Register capability</button>')+`<div class="caps">${CAPABILITIES.map(c=>`<article class="cap"><b>${c.name}</b><em>${c.risk}</em><p>${c.description}</p><code>${c.id}</code><div style="margin-top:11px;font-size:8px;color:${allowed.has(c.id)?'var(--green)':'#50656a'}">${allowed.has(c.id)?'● CONNECTED':'○ AVAILABLE'}</div></article>`).join("")}</div>`}
function memory(){return head("INSTITUTIONAL MEMORY","Memory","Only structural changes that survive evaluation and promotion become organizational knowledge.")+`<section class="panel"><div class="ph"><h3>Structural lessons</h3><small>${company.memory.length} RETAINED</small></div>${company.memory.length?company.memory.map(m=>`<div class="memory"><b>${m.title}</b><p>${m.evidence}</p></div>`).join(""):'<div class="empty">No promoted lessons yet.</div>'}</section><section class="panel" style="margin-top:18px"><div class="ph"><h3>Version history</h3><small>REVISION SAFE</small></div>${company.history.length?company.history.map(h=>`<div class="memory"><b>v${h.from} → v${h.to} · ${h.experiment}</b><p>quality ${h.qualityDelta>=0?'+':''}${(h.qualityDelta*100).toFixed(1)}pp · cost ${h.costDelta>=0?'+':''}$${h.costDelta}/day</p></div>`).join(""):'<div class="empty">Initial organization is still active.</div>'}</section>`}
function controls(){return head("CONTROL PLANE","Autonomy controls","Bound what the company may do and what evidence is required before it can change itself.",`<button class="btn danger" id="kill">${company.controls.killSwitch?'Resume company':'Kill switch'}</button>`)+`<section class="panel"><div class="control"><div><b>Guarded autonomy</b><p>Material actions stay behind explicit policy.</p></div><div class="toggle"></div></div><div class="control"><div><b>Minimum shadow cases</b><p>Evidence floor before structural promotion.</p></div><code>${company.controls.minCases}</code></div><div class="control"><div><b>Zero policy violations</b><p>Any violation blocks promotion.</p></div><div class="toggle"></div></div><div class="control"><div><b>Revision safety</b><p>A stale experiment cannot overwrite newer production.</p></div><div class="toggle"></div></div><div class="control"><div><b>Production execution</b><p>Emergency stop for autonomous actions.</p></div><b class="${company.controls.killSwitch?'bad':'good'}">${company.controls.killSwitch?'STOPPED':'ACTIVE'}</b></div></section>`}
function renderPage(){let fn={command,work,org,experiments,caps,memory,controls}[page];$("#page").innerHTML=fn();bind()}
function bind(){$("#investigate")?.addEventListener("click",()=>{experiment(company);save();page="experiments";sync();renderPage();toast("Challenger created and evaluated")});$("#newexp")?.addEventListener("click",()=>{experiment(company);save();renderPage();toast("Shadow evaluation complete")});$("#promote")?.addEventListener("click",()=>{promote(company);save();page="command";sync();render();toast(`Organization v${company.version} promoted`)});$("#rollback")?.addEventListener("click",()=>{rollback(company);save();renderPage();toast(`Rollback recorded as v${company.version}`)});$("#kill")?.addEventListener("click",()=>{company.controls.killSwitch=!company.controls.killSwitch;save();renderPage();toast(company.controls.killSwitch?"Production stopped":"Production resumed")});$("#change")?.addEventListener("click",()=>$("#switch").click());$("#register")?.addEventListener("click",()=>toast("Capability protocol accepts HTTP, MCP and local adapters"))}
function sync(){document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("on",x.dataset.p===page))}
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function render(){let e=ENVIRONMENTS[company.environment];$("#mark").textContent=e.mark;$("#cname").textContent=company.name;$("#env").textContent=e.name.toUpperCase();$("#badge").textContent=company.experiment?"1":"0";renderPage()}render();
