import assert from 'node:assert/strict';
import fs from 'node:fs';
const src=fs.readFileSync(new URL('../system.js',import.meta.url),'utf8');
assert.match(src,/api\('\/interactions'/,'new input must pass through interaction router');
assert.doesNotMatch(src,/if\(!message\|\|!operating\)return/,'composer must not silently discard messages when session hydration is missing');
assert.match(src,/await hydrateActive\(\)/,'composer must attempt authoritative rehydration');
assert.match(src,/Couldn’t send:/,'composer must surface send failures');
assert.match(src,/setInterval\(\(\)=>\{if\(active&&page==='work'/,'active work must reconcile with persisted state automatically');
assert.match(src,/companies=\[hydrated,\.\.\.companies\.filter/,'active hydrated work must be merged into recent work');
assert.doesNotMatch(src,/company\?\.data\?\.name\|\|'Untitled work'/,'hydrated UI must not retain Untitled work fallback');
assert.match(src,/const missionArtifacts=\(\)=>currentRec\('artifact'\)\.filter\(x=>\['ready','partial'\]\.includes\(x\.state\)\)/,'current mission UI must include persisted PARTIAL candidates');
assert.match(src,/const isReadyArtifact=a=>Boolean\(a&&a\.state==='ready'&&readinessOf\(a\)==='READY'&&!a\.data\?\.degraded\)/,'READY must require persisted ready state, readiness and non-degraded output');
assert.doesNotMatch(src,/rec\('artifact'\)\.filter\(x=>x\.state==='ready'\)/,'UI must not hide PARTIAL artifacts by selecting only ready records');
assert.match(src,/const artifacts=missionArtifacts\(\)/,'deliverable surface must render the newest candidate even when verification failed');
assert.match(src,/const artifactReadiness=isReadyArtifact\(persistedArtifact\)\?'READY':persistedArtifact\?'PARTIAL':null/,'top-level status must resolve any non-eligible persisted candidate to PARTIAL');
console.log('client-state-resilience: PASS');
