import assert from 'node:assert/strict';
process.env.TENSORMUX_BASE_URL='https://tensor.example';
process.env.TENSORMUX_API_KEY='tensor-test';
process.env.OPENROUTER_BASE_URL='https://openrouter.test/api/v1';
process.env.OPENROUTER_API_KEY='openrouter-test';
process.env.OPENROUTER_FALLBACK_MODEL='openrouter/free';
process.env.OPENROUTER_VERIFIER_FALLBACK_MODEL='openrouter/free';
process.env.GEMINI_BASE_URL='https://gemini.test/v1beta/openai';
process.env.GEMINI_API_KEY='gemini-test';
process.env.GEMINI_PRIMARY_MODEL='gemini-3.5-flash-lite';
process.env.GROQ_BASE_URL='https://groq.test/openai/v1';
process.env.GROQ_API_KEY='groq-test';
process.env.GROQ_VERIFIER_MODEL='openai/gpt-oss-120b';
const {routeForPolicy,providerConfigured,providerConfigSnapshot,sanitizeProviderError,completeJson,modelGatewayConfigured}=await import('../lib/model-gateway.mjs');
const {policyForRole}=await import('../lib/role-runtime.mjs');
for(const policy of ['cheap_planner','routine_executor','specialist_executor'])assert.deepEqual(routeForPolicy(policy),{policy,provider:'gemini',model:'gemini-3.5-flash-lite',strictProvider:true});
assert.deepEqual(routeForPolicy('frontier_escalation'),{policy:'frontier_escalation',provider:'openrouter',model:'openrouter/free',strictProvider:true});
assert.deepEqual(routeForPolicy('verifier'),{policy:'verifier',provider:'groq',model:'openai/gpt-oss-120b',strictProvider:true});
assert.deepEqual(routeForPolicy('verifier_fallback'),{policy:'verifier_fallback',provider:'openrouter',model:'openrouter/free',strictProvider:true});
assert.equal(modelGatewayConfigured(),true);
for(const provider of ['tensormux','openrouter','gemini','groq'])assert.equal(providerConfigured(provider),true);
assert.equal(providerConfigured('unsupported'),false);
assert.equal(providerConfigSnapshot().gemini.primaryModel,'gemini-3.5-flash-lite');
assert.equal(providerConfigSnapshot().openrouter.fallbackModel,'openrouter/free');
assert.equal(providerConfigSnapshot().openrouter.verifierFallbackModel,'openrouter/free');
assert.equal(policyForRole('brand'),'routine_executor');
assert.equal(policyForRole('finance'),'specialist_executor');
const savedFetch=globalThis.fetch,calls=[];
try{
  globalThis.fetch=async (url,opts={})=>{const body=JSON.parse(String(opts.body||'{}'));calls.push({url:String(url),headers:opts.headers,body});return new Response(JSON.stringify({id:'ok',model:body.model,choices:[{message:{content:'{"ok":true}'}}]}),{status:200,headers:{'content-type':'application/json'}})};
  await completeJson({policy:'cheap_planner',role:'planner-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'routine_executor',role:'routine-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'specialist_executor',role:'specialist-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'frontier_escalation',role:'fallback-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'verifier',role:'verify-test',system:'Return JSON',user:'{}'});
  assert.ok(calls.slice(0,3).every(x=>x.url==='https://gemini.test/v1beta/openai/chat/completions'));
  assert.equal(calls[3].url,'https://openrouter.test/api/v1/chat/completions');
  assert.equal(calls[3].body.model,'openrouter/free');
  assert.equal(calls[4].url,'https://groq.test/openai/v1/chat/completions');
  assert.equal(calls[4].body.reasoning_format,'hidden');
  assert.equal(calls[4].body.reasoning_effort,'low');
  assert.equal(calls[4].body.include_reasoning,undefined);
  await assert.rejects(()=>completeJson({policy:'verifier',provider:'openrouter',role:'bad-override',system:'Return JSON',user:'{}'}),e=>e?.message==='verifier_provider_override_forbidden');
}finally{globalThis.fetch=savedFetch}
process.env.PROVIDER_CIRCUIT_OPEN_MS='5000';
let timeoutFetches=0;
globalThis.fetch=async ()=>{timeoutFetches+=1;throw Object.assign(new Error('gemini_timeout'),{status:504})};
try{
  await assert.rejects(()=>completeJson({policy:'routine_executor',role:'circuit-first',timeoutMs:1000,system:'Return JSON',user:'{}'}),e=>e?.message==='gemini_timeout');
  await assert.rejects(()=>completeJson({policy:'routine_executor',role:'circuit-second',timeoutMs:1000,system:'Return JSON',user:'{}'}),e=>e?.message==='gemini_circuit_open');
  assert.equal(timeoutFetches,1);
}finally{globalThis.fetch=savedFetch}
assert.equal(sanitizeProviderError(Object.assign(new Error('rate'),{status:429}),'openrouter'),'openrouter_http_429');
console.log('provider-policy-reliability: PASS');
