import assert from 'node:assert/strict';
process.env.TENSORMUX_BASE_URL='https://tensor.example';
process.env.TENSORMUX_API_KEY='tensor-test';
process.env.TENSORMUX_PLANNER_MODEL='glm-planner';
process.env.TENSORMUX_EXECUTION_MODEL='glm-routine';
process.env.OPENROUTER_BASE_URL='https://openrouter.test/api/v1';
process.env.OPENROUTER_API_KEY='openrouter-test';
process.env.OPENROUTER_SPECIALIST_MODEL='openrouter/free';
process.env.GEMINI_BASE_URL='https://gemini.test/v1beta/openai';
process.env.GEMINI_API_KEY='gemini-test';
process.env.GEMINI_RECOVERY_MODEL='gemini-3.5-flash-lite';
process.env.GROQ_BASE_URL='https://groq.test/openai/v1';
process.env.GROQ_API_KEY='groq-test';
process.env.GROQ_VERIFIER_MODEL='openai/gpt-oss-120b';
const {routeForPolicy,providerConfigured,providerConfigSnapshot,sanitizeProviderError,completeJson}=await import('../lib/model-gateway.mjs');
const {policyForRole}=await import('../lib/role-runtime.mjs');
assert.deepEqual(routeForPolicy('routine_executor'),{policy:'routine_executor',provider:'tensormux',model:'glm-routine',strictProvider:false});
assert.deepEqual(routeForPolicy('specialist_executor'),{policy:'specialist_executor',provider:'openrouter',model:'openrouter/free',strictProvider:true});
assert.deepEqual(routeForPolicy('frontier_escalation'),{policy:'frontier_escalation',provider:'gemini',model:'gemini-3.5-flash-lite',strictProvider:true});
assert.deepEqual(routeForPolicy('verifier'),{policy:'verifier',provider:'groq',model:'openai/gpt-oss-120b',strictProvider:true});
for(const provider of ['tensormux','openrouter','gemini','groq'])assert.equal(providerConfigured(provider),true);
assert.equal(providerConfigured('unsupported'),false);
assert.deepEqual(Object.keys(providerConfigSnapshot()),['tensormux','openrouter','gemini','groq']);
assert.equal(policyForRole('brand'),'routine_executor');
assert.equal(policyForRole('finance'),'specialist_executor');
delete process.env.OPENROUTER_API_KEY;
assert.equal(providerConfigured('openrouter'),false);
assert.equal(routeForPolicy('specialist_executor').provider,'openrouter');
process.env.OPENROUTER_API_KEY='openrouter-test';
assert.equal(sanitizeProviderError(Object.assign(new Error('rate'),{status:429}),'openrouter'),'openrouter_http_429');
assert.equal(sanitizeProviderError(new Error('groq_invalid_response_shape'),'groq'),'groq_invalid_response_shape');
const savedFetch=globalThis.fetch,calls=[];
try{
  globalThis.fetch=async (url,opts={})=>{
    const body=JSON.parse(String(opts.body||'{}'));calls.push({url:String(url),headers:opts.headers,body});
    return new Response(JSON.stringify({id:'ok',model:body.model,choices:[{message:{content:'{"ok":true}'}}]}),{status:200,headers:{'content-type':'application/json'}});
  };
  await completeJson({policy:'specialist_executor',role:'specialist-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'frontier_escalation',role:'frontier-test',system:'Return JSON',user:'{}'});
  await completeJson({policy:'verifier',role:'verify-test',system:'Return JSON',user:'{}'});
  assert.equal(calls[0].url,'https://openrouter.test/api/v1/chat/completions');
  assert.equal(calls[0].headers?.authorization,'Bearer openrouter-test');
  assert.equal(calls[0].body?.model,'openrouter/free');
  assert.equal(calls[0].body?.provider?.require_parameters,true);
  assert.equal(calls[1].url,'https://gemini.test/v1beta/openai/chat/completions');
  assert.equal(calls[1].body?.model,'gemini-3.5-flash-lite');
  assert.equal(calls[2].url,'https://groq.test/openai/v1/chat/completions');
  assert.equal(calls[2].body?.model,'openai/gpt-oss-120b');
  assert.equal(calls[2].body?.response_format?.type,'json_object');
  calls.length=0;
  await completeJson({policy:'verifier',role:'strict-verify-test',system:'Return JSON',user:'{}',responseSchema:{type:'object',properties:{ok:{type:'boolean'}},required:['ok'],additionalProperties:false},responseSchemaName:'strict_verify'});
  assert.equal(calls[0].body?.response_format?.type,'json_schema');
  assert.equal(calls[0].body?.response_format?.json_schema?.strict,true);
  assert.equal(calls[0].body?.response_format?.json_schema?.name,'strict_verify');
  await assert.rejects(()=>completeJson({policy:'verifier',provider:'openrouter',role:'bad-override',system:'Return JSON',user:'{}'}),error=>error?.message==='verifier_provider_override_forbidden');
}finally{globalThis.fetch=savedFetch}
process.env.PROVIDER_CIRCUIT_OPEN_MS='5000';
let timeoutFetches=0;
globalThis.fetch=async ()=>{timeoutFetches+=1;throw Object.assign(new Error('openrouter_timeout'),{status:504})};
try{
  await assert.rejects(()=>completeJson({policy:'specialist_executor',role:'circuit-first',timeoutMs:1000,system:'Return JSON',user:'{}'}),error=>error?.message==='openrouter_timeout');
  await assert.rejects(()=>completeJson({policy:'specialist_executor',role:'circuit-second',timeoutMs:1000,system:'Return JSON',user:'{}'}),error=>error?.message==='openrouter_circuit_open');
  assert.equal(timeoutFetches,1,'open circuit must avoid a second network call');
}finally{globalThis.fetch=savedFetch}
console.log('provider-policy-reliability: PASS');
