import assert from 'node:assert/strict';
process.env.TENSORMUX_BASE_URL='https://tensor.example';
process.env.TENSORMUX_API_KEY='tensor-test';
process.env.TENSORMUX_PLANNER_MODEL='glm-planner';
process.env.TENSORMUX_EXECUTION_MODEL='glm-routine';
process.env.TENSORMUX_SPECIALIST_MODEL='glm-specialist';
process.env.TENSORMUX_FRONTIER_MODEL='glm-frontier';
process.env.TENSORMUX_VERIFIER_MODEL='glm-verifier';
const {routeForPolicy,providerConfigured,providerConfigSnapshot,sanitizeProviderError,completeJson}=await import('../lib/model-gateway.mjs');
const {policyForRole}=await import('../lib/role-runtime.mjs');
assert.deepEqual(routeForPolicy('routine_executor'),{policy:'routine_executor',provider:'tensormux',model:'glm-routine',strictProvider:false});
assert.deepEqual(routeForPolicy('specialist_executor'),{policy:'specialist_executor',provider:'tensormux',model:'glm-specialist',strictProvider:true});
assert.deepEqual(routeForPolicy('frontier_escalation'),{policy:'frontier_escalation',provider:'tensormux',model:'glm-frontier',strictProvider:true});
assert.deepEqual(routeForPolicy('verifier'),{policy:'verifier',provider:'tensormux',model:'glm-verifier',strictProvider:true});
assert.equal(providerConfigured('tensormux'),true);
assert.equal(providerConfigured('unsupported'),false);
assert.deepEqual(Object.keys(providerConfigSnapshot()),['tensormux']);
assert.equal(policyForRole('brand'),'routine_executor');
assert.equal(policyForRole('go_to_market'),'routine_executor');
assert.equal(policyForRole('finance'),'specialist_executor');
assert.equal(policyForRole('venture_strategy'),'specialist_executor');
delete process.env.TENSORMUX_SPECIALIST_MODEL;
assert.equal(routeForPolicy('specialist_executor').model,'glm-routine','specialist route should fall back to the configured execution model so same-route detection can refuse fake recovery');
process.env.TENSORMUX_SPECIALIST_MODEL='glm-specialist';
assert.equal(sanitizeProviderError(Object.assign(new Error('bad'),{status:401}),'tensormux'),'tensormux_http_401');
assert.equal(sanitizeProviderError(Object.assign(new Error('rate'),{status:429}),'tensormux'),'tensormux_http_429');
assert.equal(sanitizeProviderError(Object.assign(new Error('down'),{status:503}),'tensormux'),'tensormux_http_503');
assert.equal(sanitizeProviderError(Object.assign(new Error('tensormux_timeout'),{status:504}),'tensormux'),'tensormux_timeout');
assert.equal(sanitizeProviderError(new Error('tensormux_invalid_response_shape'),'tensormux'),'tensormux_invalid_response_shape');
const savedFetch=globalThis.fetch,calls=[];
try{
  globalThis.fetch=async (url,opts={})=>{calls.push({url:String(url),headers:opts.headers,body:JSON.parse(String(opts.body||'{}'))});return new Response(JSON.stringify({status:'ok'}),{status:200,headers:{'content-type':'application/json'}})};
  const telemetry=[];
  await assert.rejects(()=>completeJson({policy:'specialist_executor',role:'shape-test',onTelemetry:x=>telemetry.push(x),system:'Return JSON',user:'{}'}),error=>error?.message==='tensormux_invalid_response_shape');
  assert.equal(calls[0].url,'https://tensor.example/v1/chat/completions');
  assert.equal(calls[0].headers?.authorization,'Bearer tensor-test');
  assert.equal(calls[0].body?.model,'glm-specialist');
  assert.equal(telemetry.at(-1)?.success,false);
}finally{globalThis.fetch=savedFetch}
console.log('provider-policy-reliability: PASS');
