import assert from 'node:assert/strict';
import http from 'node:http';
import {createZyteProvider,invokeZyteCapability} from '../lib/zyte.mjs';
import {normalizeProviderInput,normalizeCapability} from '../lib/capabilities.mjs';
import {startOperatingSession} from '../lib/universal.mjs';
import {WorkerService} from '../lib/worker-service.mjs';
import {get,list,put} from '../lib/store.mjs';
import {validateOperationPlan} from '../lib/grounding.mjs';

const definition=createZyteProvider(),provider=normalizeProviderInput(definition),cap=normalizeCapability('zyte-provider',definition.manifest.capabilities[0]);assert.equal(provider.adapter,'zyte');assert.equal(cap.risk,'read');assert.equal(cap.measurements.length,0);assert.equal(cap.inputSchema.additionalProperties,false);
assert.throws(()=>validateOperationPlan([{capabilityId:'cap',args:{}}],{capabilities:[{id:'cap',data:cap}],goalContract:{desiredState:'Observe'},strategySelectionId:'strategy'}),/operation_arguments_invalid/);
const previousKey=process.env.ZYTE_API_KEY,previousUrl=process.env.ZYTE_API_URL;delete process.env.ZYTE_API_KEY;await assert.rejects(()=>invokeZyteCapability(cap,{url:'https://example.com'}),/zyte_credentials_not_configured/);
let calls=0,lastAuth='',lastPayload=null,malformed=false,failOnce=true;const server=http.createServer(async(req,res)=>{calls++;lastAuth=String(req.headers.authorization||'');const chunks=[];for await(const chunk of req)chunks.push(chunk);lastPayload=JSON.parse(Buffer.concat(chunks).toString());res.setHeader('content-type','application/json');if(failOnce){failOnce=false;res.statusCode=503;return res.end('{"type":"temporary"}')}if(malformed)return res.end('{broken');const html='<html><head><title>Observed source</title></head><body><h1>Grounded page</h1><a href="/one">One</a><a href="https://elsewhere.example/x">Away</a></body></html>';res.end(JSON.stringify({statusCode:200,httpResponseBody:Buffer.from(html).toString('base64'),httpResponseHeaders:[{name:'content-type',value:'text/html'}]}))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
try{process.env.ZYTE_API_KEY='test-only-key';process.env.ZYTE_API_URL=`http://127.0.0.1:${server.address().port}/v1/extract`;await assert.rejects(()=>invokeZyteCapability(cap,{url:'https://example.com/root'}),/zyte_http_503/);failOnce=true;const {invokeHttpCapability}=await import('../lib/capabilities.mjs');const direct=await invokeHttpCapability(cap,{...provider,adapter:'zyte'},{url:'https://example.com/root'});assert.equal(calls,3,'Zyte transient response did not retry exactly once');assert.match(lastAuth,/^Basic /);assert.deepEqual(lastPayload,{url:'https://example.com/root',httpResponseBody:true});assert.equal(direct.output.content.title,'Observed source');assert.deepEqual(direct.output.content.links,['https://example.com/one']);assert.equal(direct.output.responseMetadata.provider,'zyte');
  malformed=true;await assert.rejects(()=>invokeZyteCapability(cap,{url:'https://example.com'}),/zyte_malformed_response/);malformed=false;
  const session=await startOperatingSession({goal:'Understand the public state of an unfamiliar project',context:{operationPlan:[{capabilityName:'observe_public_webpage',args:{url:'https://example.com/root'},purpose:'Observe the user-authorized public source.',expectedObservation:['public_webpage_content']}]},providers:[definition]});for(let i=0;i<12&&(await get(session.session.id)).state!=='operating';i++)await new WorkerService({workerId:`zyte-stage-${i}`}).tick();let preRows=await list({companyId:session.company.id,limit:1000}),job=preRows.find(x=>x.kind==='job'&&x.data.operatingSessionId===session.session.id&&!x.data.operation);job.data.payload.operationPlan[0].args.url='https://payload-tampering.invalid/';await put(job,{expectedVersion:job.version});const result=await new WorkerService({workerId:'zyte-operation'}).tick();assert.equal(result.run.state,'completed');assert.equal(lastPayload.url,'https://example.com/root','mutable job payload overrode the persisted operation plan');const rows=await list({companyId:session.company.id,limit:1000}),external=rows.find(x=>x.kind==='external_observation');assert.ok(external);assert.equal(external.data.provider,'zyte');assert.equal(external.data.classification,'EXTERNAL_OBSERVATION');assert.ok(external.data.invocationId&&external.data.evidenceId&&external.data.traceId);assert.equal(external.data.requestedUrl,'https://example.com/root');const plan=rows.find(x=>x.kind==='operation_plan');assert.equal(plan.data.organizationRevisionId,result.run.data.organizationRevisionId);assert.ok(plan.data.operations[0].actorRoleId);assert.equal(plan.data.operations[0].riskLevel,'read');assert.equal(plan.data.operations[0].budgetImplications.reservationRequired,true);assert.equal(rows.filter(x=>x.kind==='outcome_observation').length,0,'unmapped Zyte content became an outcome measurement');const verification=await get(result.run.data.outcomeVerificationId);assert.equal(verification.data.outcomeAchieved,false);
  console.log('zyte-capability: PASS');
}finally{server.close();if(previousKey===undefined)delete process.env.ZYTE_API_KEY;else process.env.ZYTE_API_KEY=previousKey;if(previousUrl===undefined)delete process.env.ZYTE_API_URL;else process.env.ZYTE_API_URL=previousUrl}
