
export const ENVIRONMENTS={
 support:{name:"Customer Support",mark:"CS",outcome:"Resolve customer requests accurately without leaking sensitive data.",floor:.95,budget:30,latency:10,incident:["Sensitive-data incidents rising","Recent work contains unresolved PII exposure.","pii.redact"],caps:["data.search","policy.check","pii.redact","human.review","data.write"],roles:[["Triage","data.search"],["Resolution","policy.check"],["Publisher","data.write"]]},
 finance:{name:"Finance Operations",mark:"FO",outcome:"Process payable work accurately while preventing duplicate or invalid payments.",floor:.96,budget:45,latency:15,incident:["Duplicate-payment risk detected","Cross-record checks are missing from the current structure.","duplicate.detect"],caps:["data.search","duplicate.detect","assertion.verify","policy.check","human.review","data.write"],roles:[["Intake","data.search"],["Controller","policy.check"],["Settlement","data.write"]]},
 engineering:{name:"Software Engineering",mark:"SE",outcome:"Triage and verify repository changes while keeping risky execution behind review.",floor:.94,budget:55,latency:20,incident:["Regression rate above contract","Changes are reviewed without executable verification.","test.run"],caps:["data.search","code.inspect","test.run","policy.check","human.review"],roles:[["Triage","data.search"],["Reviewer","code.inspect"],["Release Guard","policy.check"]]}
};
export const CAPABILITIES=[
 ["data.search","Data Search","Search connected records and knowledge.","read"],["data.write","Data Write","Write a validated record to a connected system.","write"],["policy.check","Policy Check","Evaluate work against the operating constitution.","read"],["pii.redact","PII Redaction","Remove sensitive values before downstream use.","transform"],["duplicate.detect","Duplicate Detection","Compare a job with historical records.","read"],["assertion.verify","Assertion Verifier","Verify totals and factual assertions before action.","read"],["code.inspect","Code Inspector","Inspect repository changes and test evidence.","read"],["test.run","Test Runner","Execute an allowlisted test command in a sandbox.","execute"],["human.review","Human Review","Escalate a material decision to a person.","review"],["http.request","HTTP Provider","Invoke an allowlisted JSON HTTP capability.","network"]
].map(([id,name,description,risk])=>({id,name,description,risk}));
const controls=()=>({killSwitch:false,autonomy:"guarded",minCases:50,zeroViolations:true,maxCostDelta:.2});
export function seed(id="support"){const e=ENVIRONMENTS[id];return{id:`company-${id}`,environment:id,name:`${e.name} Zero`,outcome:e.outcome,version:1,quality:+(e.floor-.052).toFixed(3),cost:+(e.budget*.73).toFixed(2),latency:+(e.latency*.81).toFixed(1),roles:e.roles.map(([name,capability],i)=>({id:`r${i}`,name,capability})),capabilities:e.caps,controls:controls(),work:work(e,id),memory:[],history:[],experiment:null,incident:{title:e.incident[0],detail:e.incident[1],needed:e.incident[2]}}}
function work(e,id){const titles=id==="support"?["Refund request","Delivery issue","Account access","Invoice copy"]:id==="finance"?["Vendor invoice","Expense approval","PO reconciliation","Payment exception"]:["Pull request","CI regression","Dependency update","Release check"];return Array.from({length:24},(_,i)=>({id:`${e.mark}-${String(i+1).padStart(3,"0")}`,title:titles[i%4],risk:i%7===0?"high":i%3===0?"medium":"low",status:i%5===0?"review":"completed",duration:2+(i*3)%11,cost:+(.08+(i*.037)%1.1).toFixed(2),revision:1}))}
export function experiment(c){const needed=c.incident.needed;if(!needed)return c.experiment;const roles=c.roles.some(r=>r.capability===needed)?c.roles:[...c.roles.slice(0,-1),{id:"new",name:needed.split(".").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "),capability:needed},c.roles.at(-1)];const incumbent={quality:c.quality,cost:c.cost,latency:c.latency,violations:Math.max(1,Math.round((1-c.quality)*20)),cases:1000};const challenger={quality:+Math.min(.995,c.quality+.066).toFixed(3),cost:+Math.max(1,c.cost-.9).toFixed(2),latency:+Math.max(1,c.latency-.8).toFixed(1),violations:0,cases:1000};const gate=challenger.cases>=c.controls.minCases&&challenger.violations===0&&challenger.quality>incumbent.quality&&(challenger.cost-incumbent.cost)/incumbent.cost<=c.controls.maxCostDelta;c.experiment={id:`EXP-${18+c.history.length}`,baselineRevision:c.version,needed,roles,incumbent,challenger,gate,mode:"shadow"};return c.experiment}
export function promote(c){const x=c.experiment;if(!x?.gate)throw Error("promotion_gate_failed");if(x.baselineRevision!==c.version)throw Error("stale_revision");const old=c.version;c.version++;c.roles=x.roles;c.quality=x.challenger.quality;c.cost=x.challenger.cost;c.latency=x.challenger.latency;c.history.unshift({from:old,to:c.version,experiment:x.id,qualityDelta:+(x.challenger.quality-x.incumbent.quality).toFixed(3),costDelta:+(x.challenger.cost-x.incumbent.cost).toFixed(2),at:new Date().toISOString()});c.memory.unshift({title:`${x.needed} promoted`,evidence:`${x.challenger.cases} shadow cases · ${(x.challenger.quality*100).toFixed(1)}% quality · ${x.challenger.violations} violations`});c.experiment=null;c.incident={title:"Operating contract healthy",detail:"Current organization is inside all policy and performance bounds.",needed:null};return c}
export function rollback(c){const h=c.history[0];if(!h)return c;c.version++;c.history.unshift({from:c.version-1,to:c.version,experiment:"ROLLBACK",qualityDelta:0,costDelta:0,at:new Date().toISOString()});return c}
export function registerCapability(raw){if(!raw?.id||!raw?.name)throw Error("invalid_capability");return{id:raw.id,name:raw.name,description:raw.description||"",risk:raw.risk||"custom",permissions:raw.permissions||[],inputSchema:raw.inputSchema||{type:"object"}}}
