import {storageMode,get,list,put,audit} from './store.mjs';

const BASE=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const memory=globalThis.__CZ_CONTROL_PLANE__||(globalThis.__CZ_CONTROL_PLANE__={reservations:new Map(),remediations:new Map(),locks:new Map()});
const headers=()=>({'content-type':'application/json',apikey:KEY,authorization:`Bearer ${KEY}`});

async function rpc(name,body){const r=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const text=await r.text();let value;try{value=text?JSON.parse(text):null}catch{value=text}if(!r.ok)throw Object.assign(Error(value?.message||`rpc_${name}_failed`),{status:409});return value}
async function locked(key,fn){const prior=memory.locks.get(key)||Promise.resolve();let release;const gate=new Promise(r=>release=r),current=prior.then(()=>gate);memory.locks.set(key,current);await prior;try{return await fn()}finally{release();if(memory.locks.get(key)===current)memory.locks.delete(key)}}

export async function reserveBudget({companyId,sourceRef,amountUsd,limitUsd}){
  const amount=Number(amountUsd||0),limit=Number(limitUsd||0);if(amount<0||limit<0)throw Object.assign(Error('invalid_budget_amount'),{status:422});
  if(storageMode()==='supabase')return rpc('cz_reserve_budget',{p_company_id:companyId,p_source_ref:sourceRef,p_amount:amount,p_limit:limit});
  return locked(`budget:${companyId}`,async()=>{const existing=[...memory.reservations.values()].find(x=>x.companyId===companyId&&x.sourceRef===sourceRef);if(existing&&['reserved','consumed'].includes(existing.state))return existing.id;const used=[...memory.reservations.values()].filter(x=>x.companyId===companyId&&['reserved','consumed'].includes(x.state)).reduce((s,x)=>s+x.amountUsd,0);if(used+amount>limit)throw Object.assign(Error('budget_exceeded'),{status:409});if(existing){existing.state='reserved';existing.amountUsd=amount;return existing.id}const id=crypto.randomUUID();memory.reservations.set(id,{id,companyId,sourceRef,amountUsd:amount,state:'reserved'});return id});
}
export async function settleBudget(id,state){if(!['consumed','released'].includes(state))throw Object.assign(Error('invalid_budget_state'),{status:422});if(storageMode()==='supabase')return rpc('cz_settle_budget',{p_id:id,p_state:state});const x=memory.reservations.get(id);if(!x)throw Object.assign(Error('reservation_not_found'),{status:409});if(x.state===state)return x;if(x.state!=='reserved')throw Object.assign(Error('reservation_already_settled'),{status:409});x.state=state;return x}

export async function promoteCandidateAtomic({companyId,experimentId,candidateId}){
  if(storageMode()==='supabase')return rpc('cz_promote_candidate',{p_company:companyId,p_experiment:experimentId,p_candidate:candidateId});
  return locked(`company:${companyId}`,async()=>{const company=await get(companyId),experiment=await get(experimentId),candidate=await get(candidateId);if(!company||!experiment||!candidate)throw Object.assign(Error('promotion_subject_not_found'),{status:404});if(experiment.state!=='awaiting_decision')throw Object.assign(Error('experiment_not_ready'),{status:409});if(company.data.activeOrganizationRevisionId!==experiment.data.baselineRevisionId)throw Object.assign(Error('stale_experiment_baseline'),{status:409});const result=experiment.data.results.find(x=>x.candidateRevisionId===candidateId);if(!result||!result.constitutionPassed||result.policyStatus!=='PASS'||Number(result.uncertainCases||0)>0||Number(result.qualityDelta)<=0||Number(result.costDelta)>0||Number(result.cases)<Number(result.minCases))throw Object.assign(Error('promotion_gate_failed'),{status:409});const old=await get(experiment.data.baselineRevisionId);old.state='retired';old.data.status='retired';await put(old,{expectedVersion:old.version});candidate.kind='organization_revision';candidate.state='production';candidate.data.status='production';await put(candidate,{expectedVersion:candidate.version});company.data.activeOrganizationRevisionId=candidateId;await put(company,{expectedVersion:company.version});experiment.state='promoted';experiment.data.status='promoted';await put(experiment,{expectedVersion:experiment.version});const decision={id:crypto.randomUUID(),company_id:companyId,kind:'promotion_decision',state:'promoted',version:0,data:{experimentId,candidateRevisionId:candidateId,inputs:result}};await put(decision);const lesson={id:crypto.randomUUID(),company_id:companyId,kind:'lesson',state:'active',version:0,data:{experimentId,remediationId:experiment.data.remediationId,datasetId:experiment.data.datasetId,candidateRevisionId:candidateId,mutation:candidate.data.mutation,outcome:result,evidenceIds:experiment.data.sourceJobIds||[],decision:'promote'}};await put(lesson);await audit({company_id:companyId,actor:'promotion_rpc',action:'organization.promoted',subject_kind:'organization_revision',subject_id:candidateId,data:{experimentId}});return{decisionId:decision.id,lessonId:lesson.id}})}

export async function rollbackRevisionAtomic({companyId,targetRevisionId}){
  if(storageMode()==='supabase')return rpc('cz_rollback_revision',{p_company:companyId,p_target:targetRevisionId});
  return locked(`company:${companyId}`,async()=>{const company=await get(companyId),target=await get(targetRevisionId),current=company&&await get(company.data.activeOrganizationRevisionId);if(!company||!target||!current)throw Object.assign(Error('rollback_subject_not_found'),{status:404});const revisions=await list({companyId,limit:2000}),latest=Math.max(0,...revisions.filter(x=>['organization_revision','candidate_revision'].includes(x.kind)).map(x=>Number(x.data.revision)||0));const restored={id:crypto.randomUUID(),company_id:companyId,kind:'organization_revision',state:'production',version:0,data:{...structuredClone(target.data),revision:latest+1,parentRevisionId:current.id,status:'production',rollbackOfRevisionId:target.id}};await put(restored);current.state='retired';current.data.status='retired';await put(current,{expectedVersion:current.version});company.data.activeOrganizationRevisionId=restored.id;await put(company,{expectedVersion:company.version});await audit({company_id:companyId,actor:'rollback_rpc',action:'organization.rollback',subject_kind:'organization_revision',subject_id:restored.id,data:{fromRevisionId:current.id,targetRevisionId}});return restored})
}

export async function beginRemediation({companyId,revisionId,failureSignature,data}){
  if(storageMode()==='supabase')return rpc('cz_begin_remediation',{p_company:companyId,p_revision:revisionId,p_signature:failureSignature,p_data:data});
  return locked(`remediation:${companyId}:${revisionId}:${failureSignature}`,async()=>{const existing=[...memory.remediations.values()].find(x=>x.company_id===companyId&&x.revision_id===revisionId&&x.failure_signature===failureSignature&&['diagnosing','generating_candidates','experiment_queued','experiment_running','awaiting_decision'].includes(x.state));if(existing)return{...structuredClone(existing),created:false};const row={id:crypto.randomUUID(),company_id:companyId,revision_id:revisionId,failure_signature:failureSignature,state:'diagnosing',data:structuredClone(data),created_at:new Date().toISOString(),created:true};memory.remediations.set(row.id,row);return structuredClone(row)})
}
