import {get,list,put,audit} from './store.mjs';
import {beginRemediation} from './control-plane.mjs';
import {exportSemanticEventToNeatlogs} from './neatlogs.mjs';

const now=()=>new Date().toISOString();
const record=(kind,data,companyId,state='active')=>({id:crypto.randomUUID(),company_id:companyId,kind,state,version:0,data,created_at:now(),updated_at:now()});

export async function governProductionRun(companyId,runId){
  const run=await get(runId);if(!run||run.company_id!==companyId||run.data.shadow)return null;
  const job=await get(run.data.jobId);if(!job||job.data.experimentId)return null;
  const company=await get(companyId);if(!company||company.data.activeOrganizationRevisionId!==run.data.organizationRevisionId)return null;
  const all=await list({companyId,limit:5000}),org=all.find(x=>x.id===run.data.organizationRevisionId),mission=all.find(x=>x.kind==='mission'&&x.state==='active');
  const cfg=mission?.data?.constraints?.governor||{};
  const thresholds={windowSize:Math.max(5,Number(cfg.windowSize)||20),minimumSampleSize:Math.max(2,Number(cfg.minimumSampleSize)||5),recurringFailureCount:Math.max(2,Number(cfg.recurringFailureCount)||3),failureRateThreshold:Number(cfg.failureRateThreshold??0.5),qualityFloor:Number(cfg.qualityFloor??org?.data?.policies?.qualityFloor??0.9),costCeilingUsd:Number(cfg.costCeilingUsd??org?.data?.policies?.dailyBudgetUsd??30),latencyCeilingMs:Number(cfg.latencyCeilingMs??org?.data?.policies?.latencyLimitMs??30000),escalationThreshold:Math.max(1,Number(cfg.escalationThreshold)||3)};
  const runs=all.filter(x=>x.kind==='run'&&x.data.organizationRevisionId===run.data.organizationRevisionId&&!x.data.shadow).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,thresholds.windowSize);
  const evaluations=runs.map(r=>all.find(x=>x.id===r.data.evaluationId)).filter(Boolean),failed=evaluations.filter(x=>!x.data.passed);
  const outcomeVerifications=all.filter(x=>x.kind==='outcome_verification'&&runs.some(r=>r.id===x.data.runId)).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))),latestOutcome=outcomeVerifications[0];
  const runTraces=all.filter(x=>x.kind==='trace'&&x.data.runId===run.id),capabilityFailed=runTraces.some(x=>['failed','uncertain'].includes(x.state)),measurementMissing=latestOutcome?.data?.status==='insufficient_observation',groundedNoProgress=outcomeVerifications.filter(x=>x.data.status==='not_achieved').some(x=>(x.data.results||[]).some(r=>Number(r.change)===0));
  const rate=failed.length/Math.max(1,evaluations.length),quality=1-rate,meanCost=runs.reduce((s,x)=>s+Number(x.data.costUsd||0),0)/Math.max(1,runs.length),meanLatency=runs.reduce((s,x)=>s+Number(x.data.latencyMs||0),0)/Math.max(1,runs.length);
  const signatureFor=e=>`metric:${(e.data.results||[]).filter(r=>!r.passed).map(r=>r.metricId).sort().join(',')||'run_failure'}`,groups=new Map();for(const e of failed){const s=signatureFor(e);groups.set(s,[...(groups.get(s)||[]),e])}const [failureSignature,recurring]=[...groups.entries()].sort((a,b)=>b[1].length-a[1].length)[0]||['none',[]];
  let action='CONTINUE',reason='Evidence window remains inside adaptation thresholds.',failureClass='NONE';
  if(latestOutcome?.data?.outcomeAchieved){action='OUTCOME_ACHIEVED';reason='Independent external baseline and after observations satisfy the mission target.';failureClass='OUTCOME_ACHIEVED'}
  else if(capabilityFailed){action='REPAIR';reason='A capability invocation failed or its side-effect result is uncertain.';failureClass='CAPABILITY_FAILURE'}
  else if(meanCost>thresholds.costCeilingUsd||meanLatency>thresholds.latencyCeilingMs){action='REPAIR';reason='Operating cost or latency exceeded its configured constraint.';failureClass='CONSTRAINT_FAILURE'}
  else if(run.state==='failed'){action='RETRY';reason='An isolated runtime failure is not yet evidence of structural weakness.';failureClass='EXECUTION_FAILURE'}
  else if(measurementMissing&&outcomeVerifications.length>=thresholds.minimumSampleSize){action='REPAIR_MEASUREMENT';reason='Operations completed, but the required external baseline/after evidence is still missing.';failureClass='MEASUREMENT_FAILURE'}
  else if(evaluations.length>=thresholds.minimumSampleSize&&recurring.length>=thresholds.recurringFailureCount&&rate>=thresholds.failureRateThreshold){action='RESTRUCTURE';reason='Recurring independently evaluated failures exceeded the configured restructuring threshold.';failureClass='ORGANIZATION_FAILURE'}
  else if(outcomeVerifications.length>=thresholds.minimumSampleSize&&outcomeVerifications.every(x=>x.data.executionSucceeded&&!x.data.outcomeAchieved)){action='REPLAN_STRATEGY';reason=groundedNoProgress?'Grounded measurements show no significant progress under the current strategy.':'Grounded measurements repeatedly miss the mission target under the current strategy.';failureClass=groundedNoProgress?'NO_SIGNIFICANT_PROGRESS':'STRATEGY_FAILURE'}
  const evidenceIds=[...evaluations.map(x=>x.id),...outcomeVerifications.map(x=>x.id)],decision=record('governor_decision',{organizationRevisionId:run.data.organizationRevisionId,runId,action,reason,failureClass,evidenceIds,failureSignature,thresholdsSnapshot:thresholds,observed:{sampleSize:evaluations.length,failureCount:failed.length,recurringFailureCount:recurring.length,failureRate:rate,quality,meanCostUsd:meanCost,meanLatencyMs:meanLatency,outcomeStatus:latestOutcome?.data?.status||'not_observed'}},companyId,action.toLowerCase());Object.assign(decision,await put(decision));
  if(action==='REPAIR_MEASUREMENT'){const request=record('measurement_repair_request',{runId,organizationRevisionId:run.data.organizationRevisionId,missionId:mission?.id,missing:latestOutcome?.data?.results?.filter(x=>x.status==='insufficient_observation').map(x=>x.metricId)||[],reason,evidenceIds:outcomeVerifications.map(x=>x.id)},companyId,'queued');Object.assign(request,await put(request));decision.data.repairRequestId=request.id;Object.assign(decision,await put(decision,{expectedVersion:decision.version}))}
  if(action==='REPAIR'&&capabilityFailed){const request=record('capability_repair_request',{runId,organizationRevisionId:run.data.organizationRevisionId,capabilityIds:[...new Set(runTraces.filter(x=>['failed','uncertain'].includes(x.state)).map(x=>x.data.capabilityId).filter(Boolean))],reason,evidenceIds:runTraces.filter(x=>['failed','uncertain'].includes(x.state)).map(x=>x.id)},companyId,'queued');Object.assign(request,await put(request));decision.data.repairRequestId=request.id;Object.assign(decision,await put(decision,{expectedVersion:decision.version}))}
  if(action==='REPLAN_STRATEGY'){const request=record('replan_request',{runId,organizationRevisionId:run.data.organizationRevisionId,reason,evidenceIds:outcomeVerifications.map(x=>x.id),scope:'strategy_then_organization'},companyId,'queued');await put(request)}
  if(action==='RESTRUCTURE')decision.data.remediation=await openRemediation({companyId,revisionId:run.data.organizationRevisionId,failureSignature,evaluations:recurring,runs,all,thresholds});
  await audit({company_id:companyId,actor:'governor',action:`governor.${action.toLowerCase()}`,subject_kind:'governor_decision',subject_id:decision.id,data:{evidenceIds,failureSignature}});try{const exported=await exportSemanticEventToNeatlogs({companyId,event:'governor-decision',recordId:decision.id,state:decision.state,attributes:{'company_zero.governor.action':action,'company_zero.governor.failure_class':failureClass}});if(!exported.skipped&&!(decision.data.neatlogsTraceId)){decision.data.neatlogsTraceId=exported.trace_id||exported.traceId||null;Object.assign(decision,await put(decision,{expectedVersion:decision.version}))}}catch(error){const er=record('error',{source:'neatlogs',governorDecisionId:decision.id,message:error.message},companyId,'external_observability_failed');await put(er)}return decision;
}

async function openRemediation({companyId,revisionId,failureSignature,evaluations,runs,all,thresholds}){
  const evidenceIds=evaluations.map(x=>x.id),runIds=new Set(evaluations.map(x=>x.data.runId)),sourceJobIds=[...new Set(runs.filter(x=>runIds.has(x.id)).map(x=>x.data.jobId))];
  const remediation=await beginRemediation({companyId,revisionId,failureSignature,data:{evidenceIds,sourceJobIds,thresholdsSnapshot:thresholds}});if(!remediation.created)return{id:remediation.id,reused:true};
  const dataset=record('experiment_dataset',{remediationId:remediation.id,baselineRevisionId:revisionId,evidenceIds,sourceJobIds,failureSignature,reason:'Frozen at Governor RESTRUCTURE decision.'},companyId,'frozen');await put(dataset);
  const traces=all.filter(x=>x.kind==='trace'&&runIds.has(x.data.runId)),affectedCapabilities=[...new Set(traces.filter(x=>['failed','blocked'].includes(x.state)).map(x=>x.data.capabilityId).filter(Boolean))];
  const diagnosis=record('diagnosis',{remediationId:remediation.id,datasetId:dataset.id,organizationRevisionId:revisionId,failureMode:'Repeated metric-contract failure',failureSignature,confidence:Math.min(.95,.5+evaluations.length*.08),affectedRoles:[...new Set(traces.map(x=>x.data.roleId).filter(Boolean))],affectedRoutes:[],affectedCapabilities,recommendedMutationClasses:['AddVerifier','ChangeRouting','ChangeInstructions','ChangeBudgetAllocation'],evidenceIds},companyId);await put(diagnosis);
  const {scheduleExperiment}=await import('./experiment-service.mjs');const scheduled=await scheduleExperiment(companyId,diagnosis.id,{datasetId:dataset.id,remediationId:remediation.id});return{id:remediation.id,reused:false,datasetId:dataset.id,diagnosisId:diagnosis.id,experimentId:scheduled.experiment.id};
}
