import {get,list,put,audit,storageMode} from './store.mjs';
const URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const workIndex=globalThis.__CZ_WORK_INDEX__||(globalThis.__CZ_WORK_INDEX__=new Map());
const headers=()=>({'content-type':'application/json',apikey:KEY,authorization:`Bearer ${KEY}`});
const transitions={queued:['claimed','cancelled'],claimed:['running','retry_scheduled','dead_letter'],running:['waiting_for_approval','evaluating','retry_scheduled','uncertain','failed'],waiting_for_approval:['queued','failed','cancelled'],evaluating:['completed','failed','retry_scheduled'],retry_scheduled:['claimed','cancelled','dead_letter'],uncertain:['queued','failed','cancelled'],failed:[],completed:[],cancelled:[],dead_letter:[]};
export function assertTransition(from,to){if(!transitions[from]?.includes(to))throw Object.assign(Error(`invalid_transition:${from}->${to}`),{status:409})}
async function rpc(name,body){const r=await fetch(`${URL}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(body)}),x=await r.json();if(!r.ok)throw Error(x.message||`rpc_${name}_failed`);return x}
export async function enqueue(companyId,jobId,idempotencyKey=null){if(storageMode()==='supabase'){const x=await rpc('cz_enqueue',{p_company_id:companyId,p_job_id:jobId,p_idempotency_key:idempotencyKey});return Array.isArray(x)?x[0]:x}const q={id:crypto.randomUUID(),company_id:companyId,kind:'queue_item',state:'queued',version:0,data:{jobId,attempt:0,maxAttempts:5,availableAt:new Date().toISOString(),idempotencyKey,leaseOwner:null,leaseExpiresAt:null},created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const existing=(await list({companyId,kind:'queue_item'})).find(x=>idempotencyKey&&x.data.idempotencyKey===idempotencyKey);return existing||put(q)}
export async function ensureExperimentWork(companyId,workKey,job){if(storageMode()==='supabase'){const x=await rpc('cz_ensure_experiment_work',{p_company:companyId,p_work_key:workKey,p_job:job});return{job:x.job,queue:x.queue}}const key=`${companyId}:${workKey}`;let pending=workIndex.get(key);if(!pending){pending=(async()=>{const saved=await put(job),queue=await enqueue(companyId,saved.id,workKey);return{job:saved,queue}})();workIndex.set(key,pending);pending.catch(()=>{if(workIndex.get(key)===pending)workIndex.delete(key)})}return pending}
export async function claim(workerId,leaseSeconds=60){if(storageMode()==='supabase'){const x=await rpc('cz_claim_work',{p_worker_id:workerId,p_lease_seconds:leaseSeconds});return x[0]||null}for(const q of await list({kind:'queue_item',limit:500})){const expired=q.data.leaseExpiresAt&&new Date(q.data.leaseExpiresAt)<new Date();if(!(['queued','retry_scheduled'].includes(q.state)||(['claimed','running','evaluating'].includes(q.state)&&expired)))continue;q.state='claimed';q.data.attempt++;q.data.leaseOwner=workerId;q.data.leaseExpiresAt=new Date(Date.now()+leaseSeconds*1000).toISOString();try{return await put(q,{expectedVersion:q.version})}catch(e){if(e.message!=='stale_version')throw e}}return null}
export async function transition(item,to,{actor='runtime',reason='',evidenceIds=[]}={}){assertTransition(item.state,to);const from=item.state;if(storageMode()==='supabase'){const r=await fetch(`${URL}/rest/v1/cz_queue?id=eq.${item.id}&state=eq.${from}`,{method:'PATCH',headers:{...headers(),prefer:'return=representation'},body:JSON.stringify({state:to,updated_at:new Date().toISOString()})}),x=await r.json();if(!r.ok||!x.length)throw Object.assign(Error('concurrent_queue_transition'),{status:409});await fetch(`${URL}/rest/v1/cz_state_transitions`,{method:'POST',headers:headers(),body:JSON.stringify({company_id:item.company_id,subject_kind:'queue_item',subject_id:item.id,from_state:from,to_state:to,reason,evidence_ids:evidenceIds,actor})});return x[0]}item.state=to;const saved=await put(item,{expectedVersion:item.version});await audit({company_id:item.company_id,actor,action:'queue.transition',subject_kind:'queue_item',subject_id:item.id,data:{from,to,reason,evidenceIds}});return saved}
export async function retry(item,error,{uncertain=false}={}){if(uncertain)return transition(item,'uncertain',{reason:error});if((item.attempt||item.data?.attempt||0)>=(item.max_attempts||item.data?.maxAttempts||5))return transition(item,'dead_letter',{reason:error});if(storageMode()==='supabase'){item=await transition(item,'retry_scheduled',{reason:error});const delay=Math.min(3600,2**(item.attempt||1)*5);await fetch(`${URL}/rest/v1/cz_queue?id=eq.${item.id}`,{method:'PATCH',headers:headers(),body:JSON.stringify({available_at:new Date(Date.now()+delay*1000).toISOString(),last_error:{message:error}})});return item}item.data.availableAt=new Date(Date.now()+Math.min(3600,2**item.data.attempt*5)*1000).toISOString();return transition(item,'retry_scheduled',{reason:error})}
export async function heartbeat(workerId,currentQueueId=null,metadata={}){if(storageMode()!=='supabase')return{worker_id:workerId,current_queue_id:currentQueueId,metadata};const response=await fetch(`${URL}/rest/v1/cz_worker_heartbeats?on_conflict=worker_id`,{method:'POST',headers:{...headers(),prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({worker_id:workerId,version:'3.2',current_queue_id:currentQueueId,metadata,heartbeat_at:new Date().toISOString()})}),body=await response.json();if(!response.ok)throw Object.assign(Error(body?.message||'worker_heartbeat_failed'),{status:response.status});return body[0]||null}
export async function renewLease(item,workerId,seconds){if(storageMode()==='supabase'){const x=await rpc('cz_renew_lease',{p_queue_id:item.id,p_worker_id:workerId,p_lease_seconds:seconds});if(!x)throw Error('lease_renewal_failed');return}const x=await get(item.id);if(!x||x.data.leaseOwner!==workerId||!['claimed','running','evaluating'].includes(x.state))throw Error('lease_renewal_failed');x.data.leaseExpiresAt=new Date(Date.now()+seconds*1000).toISOString();await put(x,{expectedVersion:x.version})}
export async function getQueueItem(id){if(storageMode()==='supabase'){const r=await fetch(`${URL}/rest/v1/cz_queue?id=eq.${id}&select=*`,{headers:headers()}),x=await r.json();if(!r.ok)throw Error(x.message||'queue_read_failed');return x[0]||null}return get(id)}
export async function listWorkerHeartbeats(){if(storageMode()!=='supabase')return[];const r=await fetch(`${URL}/rest/v1/cz_worker_heartbeats?select=*&order=heartbeat_at.desc`,{headers:headers()}),x=await r.json();if(!r.ok)throw Error(x.message||'worker_heartbeat_read_failed');return x.map(row=>({...row,healthy:Date.now()-Date.parse(row.heartbeat_at)<Math.max(120000,Number(process.env.WORKER_LEASE_SECONDS||60)*2000)}))}
