import {put,get,list,audit} from './store.mjs';
import {createCompany,hydrateCompany,synthesize,launch,submitJob,registerProvider,control} from './platform-v1.mjs';
import {proposeStructured,reasoningConfigured} from './reasoning.mjs';
import {verifyOutcomeChange} from './outcome-verifier.mjs';
import {DomainError} from './contracts.mjs';
import {ensureExperimentWork} from './queue.mjs';
import {FACT_CLASSES,contextClaims,capabilityAssessment,validateOperationPlan,assessCapabilitySufficiency} from './grounding.mjs';
import {createZyteProvider,zyteConfigured} from './zyte.mjs';
import {createScrapyCloudProvider,scrapyCloudConfigured} from './scrapy-cloud.mjs';
import {createGitHubRepositoryProvider,githubRepositoryConfigured} from './github-repository.mjs';
import {createPublicHttpProbeProvider,publicHttpProbeConfigured} from './public-http-probe.mjs';

const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const record=(kind,data,companyId,state='active')=>({id:id(),company_id:companyId,kind,state,version:0,data,created_at:now(),updated_at:now()});
const cleanArray=(v,max=20)=>Array.isArray(v)?v.filter(Boolean).slice(0,max):[];
const summarizeFacts=(facts,max=50)=>cleanArray(facts,max).map(x=>{const d=x?.data||x||{};return{id:x?.id||d.id||null,classification:d.classification||FACT_CLASSES.UNKNOWN,subject:d.subject||null,predicate:d.predicate||null,value:d.value??null,sourceType:d.sourceType||null,sourceRef:d.sourceRef||null,observedAt:d.observedAt||null}});
const titleFromGoal=goal=>String(goal).replace(/[.!?]+$/,'').split(/\s+/).slice(0,6).join(' ').slice(0,72)||'New outcome';
async function reasoningProposal(args,errorCode){
  try{const proposal=await proposeStructured(args);if(!proposal&&process.env.NODE_ENV==='production')throw new DomainError(errorCode,503);return proposal}
  catch(error){if(process.env.NODE_ENV==='production'){if(error instanceof DomainError)throw error;throw new DomainError(errorCode,503,{cause:error.message})}return null}
}

function numericCriterion(goal){
  const text=String(goal);const percent=text.match(/(?:by|to|below|under|above|at least|more than)?\s*(\d+(?:\.\d+)?)\s*%/i);const count=text.match(/(?:get|reach|find|produce|generate|reduce|cut|increase|below|under|to|make|achieve)\D{0,32}(\d+(?:\.\d+)?)\s*([kmb])?/i);
  const match=percent||count;if(!match)return null;const lower=text.toLowerCase();const operator=/below|under|less|reduce|cut/.test(lower)?'<=':'>=';const suffix=percent?null:String(match[2]||'').toLowerCase();const multiplier=suffix==='k'?1_000:suffix==='m'?1_000_000:suffix==='b'?1_000_000_000:1;
  return{metricId:'outcome_metric_1',description:`Success condition: ${text}`,target:Number(match[1])*multiplier,unit:percent?'percent':'count',operator,measurementMethod:'Requires a connected capability that declares this metric and returns external evidence.',observationSources:[],attributionRequirement:'Prefer stable action and external record references.',uncertainty:'Metric definition requires confirmation against the connected system.',observationPath:'$.metrics.outcome_metric_1'};
}


export async function ensureConfiguredRuntimeProviders(companyId,{providers=[]}={}){
  let configured=[];try{configured=JSON.parse(process.env.COMPANY_ZERO_PROVIDERS_JSON||'[]')}catch{throw new DomainError('configured_provider_json_invalid',500)}
  const existing=await list({companyId,kind:'capability_provider',limit:500});
  const providerInputs=[...cleanArray(configured,20),...cleanArray(providers,10)];
  if(scrapyCloudConfigured()&&!providerInputs.some(x=>x.adapter==='scrapy-cloud'))providerInputs.push(createScrapyCloudProvider());
  else if(zyteConfigured()&&!providerInputs.some(x=>x.adapter==='zyte'))providerInputs.push(createZyteProvider());
  if(githubRepositoryConfigured()&&!providerInputs.some(x=>x.adapter==='github-repository'))providerInputs.push(createGitHubRepositoryProvider());
  if(publicHttpProbeConfigured()&&!providerInputs.some(x=>x.adapter==='public-http-probe'))providerInputs.push(createPublicHttpProbeProvider());
  const key=x=>{const adapter=String(x.adapter||'generic-http');return ['scrapy-cloud','zyte','github-repository','public-http-probe'].includes(adapter)?adapter:`${adapter}|${String(x.name||'')}|${String(x.baseUrl||'')}`};
  const seen=new Set(existing.map(x=>key(x.data||{})));
  for(const provider of providerInputs){const k=key(provider);if(seen.has(k))continue;const registered=await registerProvider(companyId,provider);seen.add(key(registered.provider.data));}
  return list({companyId,kind:'capability',limit:500});
}

export async function compileGoal(intent,{context={},constraints={}}={}){
  if(process.env.NODE_ENV==='production'&&!reasoningConfigured())throw new DomainError('tensormux_required_for_goal_compilation',503);
  const outcomeTitle=titleFromGoal(intent),fallback={desiredState:String(intent).trim(),knownCurrentState:{status:'UNKNOWN',source:'none'},successCriteria:[numericCriterion(intent)].filter(Boolean),constraints:{...constraints},deadline:constraints.deadline||null,measurementWindow:constraints.measurementWindow||null,budget:constraints.budget||constraints.dailyBudgetUsd||null,authorityBoundaries:{externalSideEffects:'approval_required',financial:'approval_required',...constraints.authorityBoundaries},requiredUnknowns:[...(context.currentState==null?[`What is available, true, or constrained right now for “${outcomeTitle}”?`]:[]),...(!numericCriterion(intent)?[`What observable result should count as “${outcomeTitle}” being done?`]:[])],attributionRequirements:['Do not infer causation from timing alone.'],uncertainty:['User-provided context remains a claim until externally observed.'],assumptions:[]};
  const proposal=await reasoningProposal({task:'Goal Compiler',instructions:'Compile arbitrary natural-language intent into an Outcome Contract: desiredState, knownCurrentState, successCriteria (metricId, description, target, operator, unit, measurementMethod, observationSources, attributionRequirement, uncertainty, observationPath), constraints, deadline, measurementWindow, budget, authorityBoundaries, requiredUnknowns, attributionRequirements, uncertainty, assumptions. Model output is a proposal, never an external fact.',input:{intent,context,constraints}},'tensormux_goal_compilation_failed');
  if(!proposal)return{...fallback,compiler:'deterministic_development_fallback'};
  const v=proposal.value||{};return{...fallback,...v,interpretedDesiredState:v.desiredState?String(v.desiredState):null,desiredState:String(intent).trim(),successCriteria:cleanArray(v.successCriteria).map((x,i)=>{const metricId=String(x.metricId||x.id||`metric_${i+1}`);const rawDescription=String(x.description||intent);const description=/\b(has successfully|has generated|successfully generated|has achieved|was achieved)\b/i.test(rawDescription)?`Success condition: ${String(intent).trim()}`:rawDescription;return{metricId,description,target:x.target,operator:['>=','<=','>','<','=','!='].includes(x.operator)?x.operator:'>=',unit:x.unit||null,measurementMethod:String(x.measurementMethod||'Requires an external observation capability.'),observationSources:cleanArray(x.observationSources),attributionRequirement:String(x.attributionRequirement||'Unknown until action and observation identities can be correlated.'),uncertainty:String(x.uncertainty||'Unquantified'),observationPath:x.observationPath||`$.metrics.${metricId}`}}),requiredUnknowns:cleanArray(v.requiredUnknowns),compiler:'tensormux',model:proposal.model,proposalOnly:true};
}

export function buildWorldModel({context={},capabilities=[],facts=[]}={}){
  const supplied=context&&typeof context==='object'?context:{};const entries=Object.entries(supplied).filter(([,v])=>v!=null);
  const counts=Object.values(FACT_CLASSES).reduce((out,key)=>(out[key]=facts.filter(x=>(x.data||x).classification===key).length,out),{});
  return{entities:cleanArray(supplied.entities),resources:cleanArray(supplied.resources),systems:cleanArray(supplied.systems),people:cleanArray(supplied.people),availableData:cleanArray(supplied.availableData),currentMetrics:supplied.currentMetrics||{},observableState:cleanArray(supplied.observableState),controllableState:cleanArray(supplied.controllableState),externalConstraints:cleanArray(supplied.externalConstraints),permissions:cleanArray(supplied.permissions),unknowns:cleanArray(supplied.unknowns),factIds:facts.map(x=>x.id).filter(Boolean),factSummaries:summarizeFacts(facts),factCounts:counts,contextKeys:entries.map(([key])=>key),capabilities:capabilities.map(capabilityAssessment),updatedAt:now()};
}

function fallbackStrategies(goalContract,worldModel,capabilities){
  const sufficiency=assessCapabilitySufficiency(goalContract,capabilities);
  const observable=capabilities.filter(c=>['observe','discover','verify'].includes(c.data.operationKind));
  const change=capabilities.filter(c=>c.data.operationKind==='change'||(c.data.changes||[]).length);
  const verify=capabilities.filter(c=>c.data.operationKind==='verify'||(c.data.measurements||[]).some(m=>(goalContract.successCriteria||[]).some(sc=>String(sc.metricId)===String(m.metricId))));
  const req=[...new Set([...observable,...change,...verify].map(x=>x.id))];
  const facts=cleanArray(worldModel.factSummaries,50),hasConcreteContext=facts.some(x=>[FACT_CLASSES.EXTERNAL_OBSERVATION,FACT_CLASSES.USER_CLAIM].includes(x.classification));
  if(!hasConcreteContext)return[
    {id:id(),title:`Ground what is available for ${titleFromGoal(goalContract.desiredState)}`,hypothesis:'A concrete recommendation requires a real description or observation of the current state.',expectedEffect:'Collect the missing current-state facts required to make the next move specific instead of generic.',evidenceRefs:[],estimatedCostUsd:null,riskLevel:'blocked',requiredCapabilityIds:req,reversibility:'not applicable',timeToEvidence:'after context is supplied',measurability:'The next strategy must cite persisted user claims or external observations.',uncertainty:'current state is unknown',constraintCompatibility:'unknown until context is grounded',operatingFunctions:['Request mission-specific context','Observe current state where possible','Replan from persisted facts']},
    {id:id(),title:`Define what can actually change for ${titleFromGoal(goalContract.desiredState)}`,hypothesis:'The system must know which resources, systems, people or constraints are controllable before proposing an intervention.',expectedEffect:'Identify a concrete control surface and the authority required to use it.',evidenceRefs:[],estimatedCostUsd:null,riskLevel:'blocked',requiredCapabilityIds:req,reversibility:'unknown until a control surface is known',timeToEvidence:'after capabilities or context are supplied',measurability:'Requires a named controllable state plus an observable success condition.',uncertainty:'control surface is unknown',constraintCompatibility:'unknown',operatingFunctions:['Identify controllable state','Check authority','Bind an execution capability']},
    {id:id(),title:`Define how ${titleFromGoal(goalContract.desiredState)} will be verified`,hypothesis:'A credible outcome requires an authoritative before/after measurement.',expectedEffect:'Bind the mission to a measurable target and a source that can verify movement.',evidenceRefs:[],estimatedCostUsd:null,riskLevel:'blocked',requiredCapabilityIds:req,reversibility:'not applicable',timeToEvidence:'after a verification source is connected',measurability:'Authoritative before/after evidence tied to the mission metric.',uncertainty:'verification source is unknown',constraintCompatibility:'unknown',operatingFunctions:['Define success metric','Bind observation source','Verify result']}
  ];
  return[
    {id:id(),title:`Use the grounded state to move ${titleFromGoal(goalContract.desiredState)}`,hypothesis:`Persisted facts can support a concrete, bounded intervention toward: ${goalContract.desiredState}`,expectedEffect:'Choose one mission-specific action supported by the current facts, then verify its effect.',evidenceRefs:worldModel.factIds||[],estimatedCostUsd:null,riskLevel:change.length?'medium':'blocked',requiredCapabilityIds:req,reversibility:'Prefer reversible actions first',timeToEvidence:'unknown',measurability:'Requires grounded baseline and authoritative after measurement',uncertainty:'depends on fact quality and capability coverage',constraintCompatibility:'bounded by the mission contract',operatingFunctions:['Use persisted facts','Design evidence-backed intervention','Execute permitted intervention','Verify outcome']},
    {id:id(),title:`Resolve the clearest known blocker to ${titleFromGoal(goalContract.desiredState)}`,hypothesis:'Progress depends on selecting a persisted constraint that an available capability can actually change.',expectedEffect:'Use the strongest current fact to identify one controllable blocker, change it, then verify whether the mission metric moved.',evidenceRefs:worldModel.factIds||[],estimatedCostUsd:null,riskLevel:sufficiency.sufficient?'low':'blocked',requiredCapabilityIds:req,reversibility:'high when the selected action supports rollback',timeToEvidence:'unknown',measurability:'Grounded before/after evidence tied to the mission metric',uncertainty:'depends on current evidence',constraintCompatibility:'bounded by the mission contract',operatingFunctions:['Identify grounded constraint','Choose controllable intervention','Execute authorized change','Measure mission result']},
    {id:id(),title:`Run the fastest verifiable move for ${titleFromGoal(goalContract.desiredState)}`,hypothesis:'A small intervention with a short measurement loop can reveal whether the selected path is working.',expectedEffect:'Select the fastest mission-specific action that is supported by persisted facts and can be measured without overclaiming.',evidenceRefs:worldModel.factIds||[],estimatedCostUsd:null,riskLevel:change.length?'unknown':'blocked',requiredCapabilityIds:req,reversibility:'unknown',timeToEvidence:'prefer shortest supported loop',measurability:'Target metric plus authoritative evidence references',uncertainty:'depends on capability coverage',constraintCompatibility:'must remain inside mission constraints',operatingFunctions:['Select supported intervention','Apply authorized change','Verify target movement']}
  ];
}

export async function searchStrategies(goalContract,worldModel,capabilities){
  if(process.env.NODE_ENV==='production'&&!reasoningConfigured())throw new DomainError('tensormux_required_for_strategy_search',503);
  const fallback=fallbackStrategies(goalContract,worldModel,capabilities);const proposal=await reasoningProposal({task:'Strategy Search',instructions:'Generate exactly three materially different, mission-specific strategy proposals. Each needs title, hypothesis, expectedEffect, evidenceRefs chosen only from supplied world fact or capability IDs, estimatedCostUsd, riskLevel, requiredCapabilityIds chosen only from supplied capabilities, reversibility, timeToEvidence, measurability, uncertainty, constraintCompatibility, and operatingFunctions. Use factSummaries as the concrete current-state input. If there are no persisted USER_CLAIM or EXTERNAL_OBSERVATION facts, do not pretend to know the world and do not recommend a concrete intervention: the three proposals must instead be distinct mission-specific grounding paths that state what must be learned, observed, or connected next. If only USER_CLAIM facts exist, you may propose a concrete move but must frame it as conditional on what the user supplied. If EXTERNAL_OBSERVATION facts exist, make titles name the actual action and target entity/system whenever the facts support that specificity. Generic slogans such as “test the safest path”, “smallest reversible path”, or merely restating the goal are invalid. Never describe model prose as evidence.',input:{goalContract,worldModel,capabilities:worldModel.capabilities}},'tensormux_strategy_search_failed');
  if(!proposal||!Array.isArray(proposal.value?.strategies))return fallback.map(x=>({...x,proposalSource:'deterministic_development_fallback'}));
  const validEvidence=new Set([...(worldModel.factIds||[]),...capabilities.map(x=>x.id)]),sufficiency=assessCapabilitySufficiency(goalContract,capabilities),strategies=proposal.value.strategies.slice(0,3).map((s,i)=>({id:id(),title:String(s.title||`Strategy ${i+1}`),hypothesis:String(s.hypothesis||''),expectedEffect:String(s.expectedEffect||''),evidenceRefs:cleanArray(s.evidenceRefs).filter(ref=>validEvidence.has(ref)),estimatedCostUsd:Number.isFinite(Number(s.estimatedCostUsd))?Number(s.estimatedCostUsd):null,riskLevel:String(s.riskLevel||'unknown'),requiredCapabilityIds:[...new Set([...cleanArray(s.requiredCapabilityIds).filter(cid=>capabilities.some(c=>c.id===cid)),...sufficiency.requiredCapabilityIds])],reversibility:s.reversibility??'unknown',timeToEvidence:s.timeToEvidence??'unknown',measurability:s.measurability??'Requires before and after observations',uncertainty:s.uncertainty??'unknown',constraintCompatibility:s.constraintCompatibility??'unknown',operatingFunctions:cleanArray(s.operatingFunctions,8),proposalSource:'tensormux',modelRequestId:proposal.requestId||null,model:proposal.model||null}));
  const critique=await reasoningProposal({task:'Strategy Critic',instructions:'Critique each supplied strategy against evidence, capability coverage, cost, risk, reversibility, measurability, constraints, and uncertainty. Return critiques containing strategyId, weaknesses, and feasibility from 0 to 1. Do not choose a winner and do not invent evidence.',input:{goalContract,worldModel,strategies}},'tensormux_strategy_critique_failed'),byId=new Map(cleanArray(critique?.value?.critiques).map(x=>[x.strategyId,x]));return strategies.map(x=>({...x,critique:byId.get(x.id)?{weaknesses:cleanArray(byId.get(x.id).weaknesses),feasibility:Math.max(0,Math.min(1,Number(byId.get(x.id).feasibility)||0)),modelRequestId:critique.requestId||null}:null}));
}

function selectStrategy(strategies,goal,capabilities){
  const available=new Set(capabilities.map(x=>x.id));const score=s=>{const required=s.requiredCapabilityIds||[],coverage=required.length?required.filter(x=>available.has(x)).length/required.length:0,grounding=Math.min(1,(s.evidenceRefs||[]).length/3),reversible=/high|reversible|prefer/i.test(String(s.reversibility))?1:/low|irreversible/i.test(String(s.reversibility))?0:.5,measurable=/before|after|metric|measure/i.test(String(s.measurability))?1:0,risk=/low/i.test(String(s.riskLevel))?1:/high/i.test(String(s.riskLevel))?0:.5,cost=s.estimatedCostUsd==null ? .25 : Math.max(0,1-Number(s.estimatedCostUsd)/100),feasibility=s.critique?Number(s.critique.feasibility||0):.5;return{total:coverage*.25+grounding*.18+reversible*.12+measurable*.17+risk*.08+cost*.05+feasibility*.15,coverage,grounding,reversible,measurable,risk,cost,feasibility}};return [...strategies].map(x=>({...x,score:score(x)})).sort((a,b)=>b.score.total-a.score.total||String(a.id).localeCompare(String(b.id)))[0];
}

async function artifact(companyId,sessionId,stage,title,items,state='completed'){
  const existing=(await list({companyId,kind:'session_artifact',limit:200})).find(x=>x.data.sessionId===sessionId&&x.data.stage===stage);if(existing)return existing;const x=record('session_artifact',{sessionId,stage,title,items:cleanArray(items,100)},companyId,state);try{await put(x);return x}catch(e){const concurrent=(await list({companyId,kind:'session_artifact',limit:200})).find(y=>y.data.sessionId===sessionId&&y.data.stage===stage);if(concurrent)return concurrent;throw e}
}
async function saveSession(session,patch){Object.assign(session.data,patch);session.state=patch.state||session.state;return put(session,{expectedVersion:session.version})}
async function queueSessionAdvance(companyId,sessionId,stage,{keySuffix=''}={}){const job=record('job',{operation:'advance_operating_session',operatingSessionId:sessionId,status:'queued',source:`operating_session:${sessionId}`,stage},companyId,'queued');const suffix=keySuffix?`:${keySuffix}`:'';return ensureExperimentWork(companyId,`operating-session:${sessionId}:stage:${stage}${suffix}`,job)}
export async function scheduleReplan(companyId,sessionId,{reason='New evidence requires another strategy',sourceRef=id(),activate=false,evidenceIds=[]}={}){const request=record('replan_request',{sessionId,reason,sourceRef,activate,evidenceIds},companyId,'queued');Object.assign(request,await put(request));const job=record('job',{operation:'replan_operating_session',operatingSessionId:sessionId,replanRequestId:request.id,status:'queued',source:`replan:${sourceRef}`},companyId,'queued');await ensureExperimentWork(companyId,`operating-session:${sessionId}:replan:${sourceRef}`,job);return request}

async function createOperationPlan({companyId,session,goalContract,missionVersion,world,selection,capabilities,organization}){
  const byName=new Map(capabilities.map(x=>[x.data.name,x.id]));let source='explicit',raw=cleanArray(session.data.context?.operationPlan,50);
  raw=raw.map(x=>({...x,capabilityId:x.capabilityId||byName.get(x.capabilityName)}));
  if(!raw.length){const proposal=await reasoningProposal({task:'Operation Planner',instructions:'Propose a minimal ordered capability plan for the selected mission-specific strategy. Return operations with capabilityId selected only from the supplied IDs, args conforming exactly to that capability inputSchema, purpose, expectedObservation, and strategySelectionId. Cover the strategy required observe, act, and verify responsibilities when they are required. Do not claim any operation has executed.',input:{goalContract,worldModel:{id:world.id,factIds:world.data.factIds,factCounts:world.data.factCounts},strategySelection:{id:selection.id,...selection.data},capabilities:capabilities.map(capabilityAssessment)}},'tensormux_operation_planning_failed');if(Array.isArray(proposal?.value?.operations)&&proposal.value.operations.length){raw=proposal.value.operations;source='tensormux'}}
  if(!raw.length){const protocolCaps=capabilities.filter(x=>x.data.acceptsMissionEnvelope);if(protocolCaps.length){raw=protocolCaps.sort((a,b)=>{const rank=x=>x.data.operationKind==='observe'&&x.data.measurements?.some(m=>m.phase==='baseline')?0:x.data.operationKind==='change'?1:2;return rank(a)-rank(b)}).map(cap=>({capabilityId:cap.id,args:{goalContract,worldModelId:world.id,strategySelectionId:selection.id},purpose:`Invoke ${cap.data.name} through its declared mission-envelope protocol.`,expectedObservation:cap.data.measurements?.map(x=>x.metricId)||[],strategySelectionId:selection.id}));source='declared_mission_envelope'}}
  if(!raw.length)return null;
  const operations=validateOperationPlan(raw,{capabilities,goalContract,strategySelectionId:selection.id,missionVersion,organization});const plan=record('operation_plan',{sessionId:session.id,missionVersion:Number(missionVersion||1),strategySelectionId:selection.id,organizationRevisionId:organization?.id||null,source,proposalOnly:false,operations},companyId,'validated');Object.assign(plan,await put(plan));return plan;
}

export async function startOperatingSession(input={}){
  const goal=String(input.goal||input.outcome||'').trim();if(!goal)throw new DomainError('goal_required');
  if(process.env.NODE_ENV==='production'&&!reasoningConfigured())throw new DomainError('tensormux_required_for_production_reasoning',503);
  const goalContract=await compileGoal(goal,{context:input.context||{},constraints:input.constraints||{}});
  const company=await createCompany({name:input.name||titleFromGoal(goal),outcome:goal,description:'Compiled from a natural-language outcome.',metrics:[],constraints:{dailyBudgetUsd:Number(goalContract.budget||input.constraints?.dailyBudgetUsd||30),qualityFloor:Number(input.constraints?.qualityFloor||.9),...input.constraints},evaluationPolicy:{type:'outcome_change',enforceMissionRelevance:true}});
  const mission=company.records.find(x=>x.kind==='mission');mission.data.goalContract=goalContract;mission.data.successCriteria=goalContract.successCriteria;Object.assign(mission,await put(mission,{expectedVersion:mission.version}));
  let session=record('operating_session',{goal,currentStage:'understanding_goal',state:'running',stageOrder:['understanding_goal','learning_world','finding_paths','choosing_strategy','building_company','equipping','starting_operations','producing_progress'],startedAt:now(),context:input.context||{},messages:[]},company.id,'running');Object.assign(session,await put(session));
  const contract=record('outcome_contract',{sessionId:session.id,missionId:mission.id,missionVersion:1,...goalContract},company.id,goalContract.successCriteria.length?'proposed':'blocked_measurement');Object.assign(contract,await put(contract));mission.data.outcomeContractId=contract.id;Object.assign(mission,await put(mission,{expectedVersion:mission.version}));
  const claims=[];for(const data of contextClaims(input.context||{})){const fact=record('world_fact',{sessionId:session.id,...data},company.id,'claimed');Object.assign(fact,await put(fact));claims.push(fact)}
  if(input.context?.currentMetrics&&Object.keys(input.context.currentMetrics).length){const baseline=record('outcome_observation',{sessionId:session.id,missionVersion:1,sourceType:'user',source:'user_context',phase:'baseline',classification:FACT_CLASSES.USER_CLAIM,metrics:input.context.currentMetrics,evidenceIds:claims.filter(x=>x.data.predicate.startsWith('metric:')).map(x=>x.id),observedAt:now(),confidence:null,notes:'User-claimed baseline; it cannot independently prove outcome success.'},company.id,'claimed');await put(baseline)}
  await artifact(company.id,session.id,'understanding_goal','Outcome contract',[{type:'desired_state',label:goalContract.desiredState,claimType:'MODEL_PROPOSAL',sourceRefs:[contract.id]},{type:'constraint_count',label:`${Object.keys(goalContract.constraints||{}).length} constraints parsed`,claimType:'MODEL_PROPOSAL',sourceRefs:[contract.id]},{type:'success_criteria',label:goalContract.successCriteria.length?`${goalContract.successCriteria.length} proposed success criteria`:'Measurement definition required',claimType:'MODEL_PROPOSAL',sourceRefs:[contract.id]}],goalContract.successCriteria.length?'completed':'blocked');
  const capabilities=await ensureConfiguredRuntimeProviders(company.id,{providers:input.providers||[]});for(const cap of capabilities){const assessment=record('capability_assessment',{sessionId:session.id,...capabilityAssessment(cap)},company.id,'declared');await put(assessment)}
  session=await saveSession(session,{currentStage:'learning_world',state:'running'});await queueSessionAdvance(company.id,session.id,'learning_world');return hydrateOperatingSession(company.id,session.id);
}

export async function advanceOperatingSession(companyId,sessionId,{singleStage=false}={}){
  let session=await get(sessionId);if(!session||session.company_id!==companyId||session.kind!=='operating_session')throw new DomainError('operating_session_not_found',404);
  const records=await list({companyId,limit:3000}),mission=records.find(x=>x.kind==='mission'&&x.state==='active'),capabilities=records.filter(x=>x.kind==='capability'),goalContract=mission?.data?.goalContract||await compileGoal(mission?.data?.outcome||session.data.goal,{context:session.data.context});
  let world=records.filter(x=>x.kind==='world_model').sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))[0];
  if(!world){const facts=records.filter(x=>x.kind==='world_fact'&&x.data.sessionId===sessionId);world=record('world_model',{sessionId,...buildWorldModel({context:session.data.context,capabilities,facts})},companyId);Object.assign(world,await put(world));const external=facts.filter(x=>x.data.classification===FACT_CLASSES.EXTERNAL_OBSERVATION);await artifact(companyId,sessionId,'learning_world','Grounded world ledger',[{type:'fact_count',label:`${facts.length} user claims recorded`,claimType:'USER_CLAIM',sourceRefs:facts.map(x=>x.id)},{type:'observation_count',label:`${external.length} external observations`,claimType:'EXTERNAL_OBSERVATION',sourceRefs:external.map(x=>x.id)},{type:'capability_count',label:`${capabilities.length} declared capabilities`,claimType:'DECLARED_CAPABILITY',sourceRefs:records.filter(x=>x.kind==='capability_assessment').map(x=>x.id)},{type:'unknown_count',label:`${world.data.unknowns.length+goalContract.requiredUnknowns.length} unresolved unknowns`,claimType:'UNKNOWN',sourceRefs:[world.id]}],external.length?'completed':'provisional');if(singleStage){session=await saveSession(session,{currentStage:'finding_paths',state:'running'});await queueSessionAdvance(companyId,sessionId,'finding_paths');return hydrateOperatingSession(companyId,sessionId)}}
  else if((world.data.capabilities||[]).length!==capabilities.length){world.data.capabilities=capabilities.map(capabilityAssessment);world.data.updatedAt=now();Object.assign(world,await put(world,{expectedVersion:world.version}));const assessed=new Set(records.filter(x=>x.kind==='capability_assessment'&&x.data.sessionId===sessionId).map(x=>x.data.id));for(const cap of capabilities.filter(x=>!assessed.has(x.id))){const assessment=record('capability_assessment',{sessionId,...capabilityAssessment(cap)},companyId,'declared');await put(assessment)}const worldStage=records.find(x=>x.kind==='session_artifact'&&x.data.sessionId===sessionId&&x.data.stage==='learning_world');if(worldStage){const items=cleanArray(worldStage.data.items,20).filter(x=>x.type!=='capability_count');const refs=(await list({companyId,kind:'capability_assessment',limit:500})).filter(x=>x.data.sessionId===sessionId).map(x=>x.id);worldStage.data.items=[...items,{type:'capability_count',label:`${capabilities.length} declared capabilities`,claimType:'DECLARED_CAPABILITY',sourceRefs:refs}];Object.assign(worldStage,await put(worldStage,{expectedVersion:worldStage.version}))}for(const x of records.filter(x=>['strategy_option','strategy_selection'].includes(x.kind)&&x.data.sessionId===sessionId&&x.state!=='superseded')){x.state='superseded';await put(x,{expectedVersion:x.version})}for(const request of records.filter(x=>x.kind==='capability_access_request'&&x.state==='open')){request.state='resolved';request.data.resolvedAt=now();await put(request,{expectedVersion:request.version})}}
  const currentFacts=records.filter(x=>x.kind==='world_fact'&&x.data.sessionId===sessionId),factSummaries=summarizeFacts(currentFacts),factIds=currentFacts.map(x=>x.id).filter(Boolean);if(JSON.stringify(world.data.factIds||[])!==JSON.stringify(factIds)||JSON.stringify(world.data.factSummaries||[])!==JSON.stringify(factSummaries)){world.data.factIds=factIds;world.data.factSummaries=factSummaries;world.data.factCounts=Object.values(FACT_CLASSES).reduce((out,key)=>(out[key]=currentFacts.filter(x=>x.data.classification===key).length,out),{});world.data.updatedAt=now();Object.assign(world,await put(world,{expectedVersion:world.version}))}
  let strategyRecords=records.filter(x=>x.kind==='strategy_option'&&x.data.sessionId===sessionId&&x.state==='considered');
  if(!strategyRecords.length){const strategies=await searchStrategies(goalContract,world.data,capabilities);for(const strategy of strategies){const x=record('strategy_option',{sessionId,claimType:'MODEL_PROPOSAL',...strategy},companyId,'considered');Object.assign(x,await put(x));strategyRecords.push(x)}await artifact(companyId,sessionId,'finding_paths','Strategy proposals',strategyRecords.map(x=>({type:'strategy',id:x.id,label:x.data.title,detail:x.data.expectedEffect,claimType:'MODEL_PROPOSAL',sourceRefs:[x.id,...(x.data.evidenceRefs||[])]})));if(singleStage){session=await saveSession(session,{currentStage:'choosing_strategy',state:'running'});await queueSessionAdvance(companyId,sessionId,'choosing_strategy');return hydrateOperatingSession(companyId,sessionId)}}
  let selection=(await list({companyId,kind:'strategy_selection',limit:100})).find(x=>x.data.sessionId===sessionId&&x.state==='selected');
  if(!selection){const selected=selectStrategy(strategyRecords.map(x=>({...x.data,id:x.id})),goalContract.desiredState,capabilities),externalFacts=records.filter(x=>x.kind==='world_fact'&&x.data.sessionId===sessionId&&x.data.classification===FACT_CLASSES.EXTERNAL_OBSERVATION),userFacts=records.filter(x=>x.kind==='world_fact'&&x.data.sessionId===sessionId&&x.data.classification===FACT_CLASSES.USER_CLAIM);selection=record('strategy_selection',{sessionId,strategyId:selected.id,title:selected.title,rationale:`Selected by the persisted score across capability coverage, evidence grounding, reversibility, measurability, risk and cost. External evidence available: ${externalFacts.length}. User-supplied facts available: ${userFacts.length}.`,score:selected.score,evidenceRefs:selected.evidenceRefs||[],evidenceMaturity:externalFacts.length?'externally_grounded':userFacts.length?'user_grounded':'hypothesis_only',requiredCapabilityIds:selected.requiredCapabilityIds,operatingFunctions:selected.operatingFunctions},companyId,'selected');Object.assign(selection,await put(selection));await artifact(companyId,sessionId,'choosing_strategy','Selected strategy proposal',[{type:'selection',label:selected.title,detail:selection.data.rationale,claimType:'MODEL_PROPOSAL',sourceRefs:[selection.id,...selection.data.evidenceRefs]}],externalFacts.length?'completed':'provisional');if(singleStage){session=await saveSession(session,{currentStage:capabilities.length?'building_company':'equipping',state:'running'});await queueSessionAdvance(companyId,sessionId,session.data.currentStage);return hydrateOperatingSession(companyId,sessionId)}}
  if(!capabilities.length){let request=(await list({companyId,kind:'capability_access_request',limit:100})).find(x=>x.state==='open');if(!request){const concreteFacts=records.filter(x=>x.kind==='world_fact'&&x.data.sessionId===sessionId&&[FACT_CLASSES.USER_CLAIM,FACT_CLASSES.EXTERNAL_OBSERVATION].includes(x.data.classification)),unknowns=cleanArray(goalContract.requiredUnknowns,6),firstNeed=unknowns[0]||goalContract.successCriteria?.[0]?.description||'the current state';const noGrounding=!concreteFacts.length;request=record('capability_access_request',{sessionId,reasonCode:noGrounding?'grounding_and_capability_required':'capability_required',reason:noGrounding?'Company Zero needs mission-specific current-state context before a real move can be recommended, and a real capability before it can act or verify.':'Company Zero has context for the mission but no real capability that can observe or change the world.',neededFromUser:unknowns,neededToObserve:[...unknowns,...goalContract.successCriteria.map(x=>x.description)].filter(Boolean),neededToChange:[goalContract.desiredState],message:noGrounding?`I need to know what I’m working with before I recommend a real move. Start with: ${firstNeed}. Add that context below or connect a source that can observe it. I’ll still need a real capability before I can execute or verify anything.`:`I can reason from the context you supplied, but I still need a real capability that can observe the target, act within your authority, and verify the result.`},companyId,'open');await put(request);await artifact(companyId,sessionId,'equipping','Capability access required',[{type:'blocker',label:request.data.message}], 'blocked')}
    session=await saveSession(session,{currentStage:'equipping',state:'awaiting_capabilities',blockerId:request.id});return hydrateOperatingSession(companyId,session.id);
  }
  const sufficiency=assessCapabilitySufficiency(goalContract,capabilities);
  if(!sufficiency.sufficient){
    let request=(await list({companyId,kind:'capability_access_request',limit:100})).find(x=>x.state==='open'&&x.data.reasonCode==='outcome_capability_insufficient');
    if(!request){
      const missingKinds=sufficiency.missing.map(x=>x.kind);
      request=record('capability_access_request',{sessionId,reasonCode:'outcome_capability_insufficient',reason:'Available capabilities cannot yet cover the minimum observe / act / verify requirements for this mission.',missingKinds,capabilityRequirements:sufficiency.requirements,availableBindings:sufficiency.bindings,neededToObserve:sufficiency.missing.filter(x=>x.kind==='observe'||x.kind==='verify').map(x=>x.reason),neededToChange:sufficiency.missing.filter(x=>x.kind==='act').map(x=>x.reason),message:`I can ${sufficiency.bindings.observe.length?'observe part of this mission':'plan from the information provided'}, but I still need ${missingKinds.join(' and ')} capability coverage before I can honestly execute and verify the outcome.`},companyId,'open');
      Object.assign(request,await put(request));
      await artifact(companyId,sessionId,'equipping','Capability access required',[{type:'blocker',label:request.data.message,claimType:'BLOCKER',sourceRefs:[request.id]}],'blocked');
    }
    session=await saveSession(session,{currentStage:'equipping',state:'awaiting_capabilities',blockerId:request.id,selectedStrategyId:selection.data.strategyId});
    return hydrateOperatingSession(companyId,session.id);
  }
  let org=records.filter(x=>x.kind==='organization_revision'&&['candidate','production'].includes(x.state)).sort((a,b)=>(b.data.revision||0)-(a.data.revision||0))[0];
  if(!org){const selected=strategyRecords.find(x=>x.id===selection.data.strategyId)?.data||selection.data;org=await synthesize(companyId,{goalContract,worldModel:{id:world.id,...world.data},strategy:{...selected,selectionId:selection.id},availableCapabilities:capabilities});await artifact(companyId,sessionId,'building_company','Company revision proposed',(org.data.roles||[]).map(r=>({type:'role',id:r.id,label:r.name,detail:r.purpose,claimType:'RUNTIME_STATE',sourceRefs:[org.id]})));if(singleStage){session=await saveSession(session,{currentStage:'equipping',state:'running'});await queueSessionAdvance(companyId,sessionId,'equipping');return hydrateOperatingSession(companyId,sessionId)}}
  if(org.state==='candidate'){org=await launch(companyId,org.id);if(!(await list({companyId,kind:'session_artifact',limit:100})).some(x=>x.data.sessionId===sessionId&&x.data.stage==='equipping'))await artifact(companyId,sessionId,'equipping','Declared capabilities assigned',(org.data.roles||[]).map(r=>({type:'assignment',label:`${r.name}: ${(r.capabilityIds||[]).length} declared capabilities`,capabilityIds:r.capabilityIds,claimType:'DECLARED_CAPABILITY',sourceRefs:r.capabilityIds})));if(singleStage){session=await saveSession(session,{currentStage:'starting_operations',state:'running'});await queueSessionAdvance(companyId,sessionId,'starting_operations');return hydrateOperatingSession(companyId,sessionId)}}
  let job=(await list({companyId,kind:'job',limit:500})).find(x=>x.data.operatingSessionId===sessionId&&!x.data.operation);
  if(!job){const plan=await createOperationPlan({companyId,session,goalContract,missionVersion:mission?.data?.version,world,selection,capabilities,organization:org});if(!plan){let request=(await list({companyId,kind:'capability_access_request',limit:100})).find(x=>x.state==='open'&&x.data.reasonCode==='operation_plan_unavailable');if(!request){request=record('capability_access_request',{sessionId,reasonCode:'operation_plan_unavailable',reason:'No validated operation plan can be produced from the available capability schemas without configured reasoning or a declared mission-envelope protocol.',neededToObserve:goalContract.successCriteria.map(x=>x.metricId),neededToChange:[goalContract.desiredState],message:'The capabilities are declared, but I cannot safely map this goal into valid capability inputs. Configure TensorMux or connect a capability that accepts the standard mission envelope.'},companyId,'open');await put(request);await artifact(companyId,sessionId,'starting_operations','Operation blocked',[{type:'blocker',label:request.data.message,claimType:'BLOCKER',sourceRefs:[request.id]}], 'blocked')}session=await saveSession(session,{currentStage:'starting_operations',state:'awaiting_operation_plan',blockerId:request.id,organizationRevisionId:org.id,selectedStrategyId:selection.data.strategyId});return hydrateOperatingSession(companyId,session.id)}job=await submitJob(companyId,{goalContract,worldModelId:world.id,strategySelectionId:selection.id,operationPlanId:plan.id,operationPlan:plan.data.operations},{idempotencyKey:`operating-session:${sessionId}:initial`,source:`operating_session:${sessionId}`});job.data.operatingSessionId=sessionId;Object.assign(job,await put(job,{expectedVersion:job.version}));await artifact(companyId,sessionId,'starting_operations','Durable operation plan queued',[{type:'job',id:job.id,label:`${plan.data.operations.length} validated operation${plan.data.operations.length===1?'':'s'} queued`,detail:`Pinned to organization revision ${job.data.organizationRevision}`,claimType:'RUNTIME_STATE',sourceRefs:[job.id,plan.id]}]);}
  session=await saveSession(session,{currentStage:'producing_progress',state:'operating',organizationRevisionId:org.id,jobId:job.id,selectedStrategyId:selection.data.strategyId});return hydrateOperatingSession(companyId,session.id);
}

export async function hydrateOperatingSession(companyId,sessionId){const session=await get(sessionId);if(!session||session.company_id!==companyId)throw new DomainError('operating_session_not_found',404);const records=await list({companyId,limit:3000});return{session,company:await hydrateCompany(await get(companyId)),artifacts:records.filter(x=>x.kind==='session_artifact'&&x.data.sessionId===sessionId).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))),strategies:records.filter(x=>x.kind==='strategy_option'&&x.data.sessionId===sessionId),messages:records.filter(x=>x.kind==='conversation_message'&&x.data.sessionId===sessionId).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)))}}

export async function replanOperatingSession(companyId,sessionId,replanRequestId){
  if(process.env.NODE_ENV==='production'&&!reasoningConfigured())throw new DomainError('tensormux_required_for_replanning',503);
  let session=await get(sessionId),request=await get(replanRequestId);if(!session||session.company_id!==companyId||!request||request.company_id!==companyId)throw new DomainError('replan_request_not_found',404);
  const records=await list({companyId,limit:3000}),mission=records.find(x=>x.kind==='mission'&&x.state==='active'),world=records.filter(x=>x.kind==='world_model').sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0],capabilities=records.filter(x=>x.kind==='capability');
  if(!capabilities.length){request.state='blocked';request.data.blocker='capabilities_required';await put(request,{expectedVersion:request.version});return hydrateOperatingSession(companyId,sessionId)}
  for(const x of records.filter(x=>['strategy_option','strategy_selection'].includes(x.kind)&&x.data.sessionId===sessionId&&['considered','selected'].includes(x.state))){x.state='superseded';await put(x,{expectedVersion:x.version})}
  const strategies=await searchStrategies(mission.data.goalContract,world.data,capabilities),created=[];for(const strategy of strategies){const x=record('strategy_option',{sessionId,replanRequestId,claimType:'MODEL_PROPOSAL',...strategy},companyId,'considered');Object.assign(x,await put(x));created.push(x)}
  const selected=selectStrategy(created.map(x=>({...x.data,id:x.id})),mission.data.goalContract.desiredState,capabilities),selection=record('strategy_selection',{sessionId,replanRequestId,strategyId:selected.id,title:selected.title,rationale:`Replanned from ${request.data.evidenceIds?.length||0} persisted evidence records; score ${selected.score.total.toFixed(3)}.`,score:selected.score,evidenceRefs:selected.evidenceRefs||[],evidenceMaturity:(request.data.evidenceIds?.length||0)?'evidence_driven':'user_directed',requiredCapabilityIds:selected.requiredCapabilityIds,operatingFunctions:selected.operatingFunctions},companyId,'selected');Object.assign(selection,await put(selection));
  const org=await synthesize(companyId,{goalContract:mission.data.goalContract,worldModel:{id:world.id,...world.data},strategy:{...selected,selectionId:selection.id},availableCapabilities:capabilities});request.data.proposedStrategyId=selected.id;request.data.proposedOrganizationRevisionId=org.id;
  if(request.data.activate){const plan=await createOperationPlan({companyId,session,goalContract:mission.data.goalContract,missionVersion:mission.data.version,world,selection,capabilities,organization:org});if(!plan){request.state='blocked';request.data.blocker='operation_plan_unavailable';session.state='awaiting_operation_plan';session.data.state='awaiting_operation_plan';session.data.currentStage='starting_operations';await put(session,{expectedVersion:session.version})}else{await launch(companyId,org.id);const job=await submitJob(companyId,{goalContract:mission.data.goalContract,worldModelId:world.id,strategySelectionId:selection.id,operationPlanId:plan.id,operationPlan:plan.data.operations},{idempotencyKey:`replan:${request.id}:first-operation`,source:`operating_session:${sessionId}`});job.data.operatingSessionId=sessionId;await put(job,{expectedVersion:job.version});session.data.organizationRevisionId=org.id;session.data.jobId=job.id;session.data.selectedStrategyId=selected.id;await put(session,{expectedVersion:session.version});request.state='activated'}}else request.state='awaiting_experiment';
  await put(request,{expectedVersion:request.version});return hydrateOperatingSession(companyId,sessionId)
}

export async function recordObservation(companyId,input={}){const session=await get(input.sessionId);if(!session||session.company_id!==companyId)throw new DomainError('operating_session_not_found',404);const observation=record('outcome_observation',{sessionId:session.id,missionVersion:null,sourceType:'user',source:'user_report',phase:input.phase||'observation',classification:FACT_CLASSES.USER_CLAIM,metrics:input.metrics||{},before:input.before,after:input.after,evidenceIds:[],reportedEvidenceRefs:cleanArray(input.evidenceIds),observedAt:input.observedAt||now(),confidence:null,notes:input.notes||''},companyId,'claimed');Object.assign(observation,await put(observation));const records=await list({companyId,limit:3000}),mission=records.find(x=>x.kind==='mission'&&x.state==='active'),job=records.find(x=>x.id===session.data.jobId),run=job?.data?.runId?await get(job.data.runId):null,observations=records.filter(x=>x.kind==='outcome_observation');const verdict=verifyOutcomeChange({goalContract:mission?.data?.goalContract,observations,executionStatus:run?.data?.status,sessionId:session.id,missionVersion:job?.data?.missionVersion});const verification=record('outcome_verification',{sessionId:session.id,runId:run?.id||null,missionVersion:job?.data?.missionVersion,...verdict},companyId,verdict.status);Object.assign(verification,await put(verification));await artifact(companyId,session.id,'producing_progress','Outcome evidence status',verdict.results.map(x=>({type:'metric',label:x.description||x.metricId,before:x.before,after:x.after,target:x.target,status:x.status,attributionStatus:x.attributionStatus,claimType:'VERIFICATION',sourceRefs:[verification.id,...x.evidenceIds]})),verdict.status);return{observation,verification}}

function fallbackConversation(text,mission,records){const lower=text.toLowerCase(),target=lower.match(/(?:change|set|make)\s+(?:the\s+)?target\s+(?:to\s+)?(\d+(?:\.\d+)?)/),budget=lower.match(/(?:budget|spend)(?:\s+to)?\s*[$₦£€]?\s*(\d+(?:\.\d+)?)/),criteria=mission?.data?.goalContract?.successCriteria||[];const why=/^\s*why\b/.test(lower),selection=records.find(x=>x.kind==='strategy_selection'&&x.state==='selected');return{changeType:target?'goal':budget?'constraints':/don't|do not|without asking|stop|pause/.test(lower)?'authority':/different approach|another route|not what i meant/.test(lower)?'strategy':'context',summary:text,goalPatch:target?{successCriteria:criteria.map((x,i)=>i?x:{...x,target:Number(target[1])})}:{},constraintPatch:budget?{dailyBudgetUsd:Number(budget[1])}:/spend less/.test(lower)?{budgetDirection:'decrease'}:{},authorityPatch:/don't|do not|without asking/.test(lower)?{externalSideEffects:'approval_required'}:{},worldPatch:why?{}:{userCorrection:text},requiresReplan:Boolean(target||/different approach|another route|not what i meant|change the target/.test(lower)),requiresRestructure:false,pauseRequested:/\bstop|pause\b/.test(lower),answer:why?(selection?.data?.rationale||'The current approach was selected from the available evidence, capabilities, risk and measurability.'):target?`I changed the target to ${target[1]} and marked the strategy for replanning.`:budget?`I set the operating budget to ${budget[1]}.`:'I recorded this correction without discarding the original evidence.'}}

export async function converse(companyId,sessionId,message){const text=String(message||'').trim();if(!text)throw new DomainError('message_required');if(process.env.NODE_ENV==='production'&&!reasoningConfigured())throw new DomainError('tensormux_required_for_conversation_interpretation',503);let session=await get(sessionId);if(!session||session.company_id!==companyId)throw new DomainError('operating_session_not_found',404);const records=await list({companyId,limit:3000}),mission=records.find(x=>x.kind==='mission'&&x.state==='active'),company=await get(companyId);const proposal=await reasoningProposal({task:'Conversation Interpreter',instructions:'Interpret the user message as a possible correction to the goal, constraints, authority, world model, strategy, or organization. Return changeType, summary, goalPatch, constraintPatch, authorityPatch, worldPatch, requiresReplan, requiresRestructure, pauseRequested, answer. Preserve user authority.',input:{message:text,goalContract:mission?.data?.goalContract,session:session.data}},'tensormux_conversation_interpretation_failed');const change=proposal?.value||fallbackConversation(text,mission,records);const msg=record('conversation_message',{sessionId,role:'user',content:text,interpretedChange:change},companyId,'recorded');await put(msg);
  if(change.pauseRequested)await control(companyId,'pause');
  const patches=[change.goalPatch,change.constraintPatch,change.authorityPatch].some(x=>x&&Object.keys(x).length);
  if(patches){mission.state='superseded';await put(mission,{expectedVersion:mission.version});const nextContract={...mission.data.goalContract,...change.goalPatch,constraints:{...(mission.data.goalContract?.constraints||{}),...(change.constraintPatch||{})},authorityBoundaries:{...(mission.data.goalContract?.authorityBoundaries||{}),...(change.authorityPatch||{})}};const next=record('mission',{...mission.data,outcome:nextContract.desiredState||mission.data.outcome,goalContract:nextContract,successCriteria:nextContract.successCriteria||mission.data.successCriteria,version:Number(mission.data.version||1)+1,previousMissionId:mission.id},companyId,'active');Object.assign(next,await put(next));const contract=record('outcome_contract',{sessionId,missionId:next.id,missionVersion:next.data.version,...nextContract},companyId,'proposed');Object.assign(contract,await put(contract));next.data.outcomeContractId=contract.id;await put(next,{expectedVersion:next.version});company.data.missionId=next.id;company.data.missionVersion=Number(company.data.missionVersion||1)+1;await put(company,{expectedVersion:company.version});}
  const contextChanged=Boolean(change.worldPatch&&Object.keys(change.worldPatch).length);if(contextChanged){const world=records.find(x=>x.kind==='world_model');if(world){const factIds=[];for(const [key,value] of Object.entries(change.worldPatch)){const fact=record('world_fact',{sessionId,subject:'context',predicate:key,value,classification:FACT_CLASSES.USER_CLAIM,sourceType:'user',sourceRef:`conversation:${msg.id}`,observedAt:now(),confidence:null,evidenceIds:[msg.id]},companyId,'claimed');Object.assign(fact,await put(fact));factIds.push(fact.id)}world.data.factIds=[...(world.data.factIds||[]),...factIds];const createdFacts=await Promise.all(factIds.map(fid=>get(fid)));world.data.factSummaries=[...cleanArray(world.data.factSummaries,50),...summarizeFacts(createdFacts)].slice(-50);world.data.factCounts={...(world.data.factCounts||{}),USER_CLAIM:Number(world.data.factCounts?.USER_CLAIM||0)+factIds.length};world.data.updatedAt=now();await put(world,{expectedVersion:world.version})}}
  if(change.requiresReplan)await scheduleReplan(companyId,sessionId,{reason:change.summary||text,sourceRef:`message:${msg.id}`,activate:true,evidenceIds:[]});else if(contextChanged&&['awaiting_capabilities','awaiting_operation_plan'].includes(session.state)){for(const row of records.filter(x=>['strategy_option','strategy_selection'].includes(x.kind)&&x.data.sessionId===sessionId&&x.state!=='superseded')){row.state='superseded';await put(row,{expectedVersion:row.version})}for(const request of records.filter(x=>x.kind==='capability_access_request'&&x.data.sessionId===sessionId&&x.state==='open')){request.state='resolved';request.data.resolvedAt=now();await put(request,{expectedVersion:request.version})}session=await saveSession(session,{currentStage:'finding_paths',state:'running'});await queueSessionAdvance(companyId,sessionId,'finding_paths',{keySuffix:`context:${msg.id}`})}
  const reply=record('conversation_message',{sessionId,role:'company_zero',content:String(change.answer||'Correction recorded.'),changeType:change.changeType||'context',requiresReplan:Boolean(change.requiresReplan),requiresRestructure:Boolean(change.requiresRestructure)},companyId,'recorded');await put(reply);await audit({company_id:companyId,actor:'user',action:'operating_session.corrected',subject_kind:'operating_session',subject_id:sessionId,data:{messageId:msg.id,changeType:change.changeType}});return{message:msg,reply,change}}
