import {DomainError,validateSchema} from './contracts.mjs';
import {safeUrl} from './capabilities.mjs';

const MAX_RESPONSE_BYTES=1_000_000,MAX_EXTRACTED_CHARS=200_000,MAX_LINKS=50;
const apiUrl=()=>process.env.ZYTE_API_URL||'https://api.zyte.com/v1/extract';

export function zyteConfigured(){return Boolean(process.env.ZYTE_API_KEY)}

export function createZyteProvider(){return{name:'Zyte public-web observation',type:'http',adapter:'zyte',baseUrl:'https://api.zyte.com',headers:{},manifest:{capabilities:[{name:'observe_public_webpage',description:'Fetch one explicitly requested public webpage through Zyte and return bounded source-backed page content. This observes; it does not prove a mission outcome.',endpoint:'/v1/extract',method:'POST',risk:'read',operationKind:'observe',observes:['public_webpage_content','public_webpage_metadata'],changes:[],permissions:['public_web.read','single_url_only'],acceptsMissionEnvelope:false,inputSchema:{type:'object',required:['url'],additionalProperties:false,properties:{url:{type:'string',minLength:8,maxLength:2048},renderBrowser:{type:'boolean'}}},outputSchema:{type:'object',required:['sourceUrl','observedAt','content','responseMetadata'],properties:{sourceUrl:{type:'string'},observedAt:{type:'string'},content:{type:'object'},responseMetadata:{type:'object'}}},estimatedCost:{type:'per_call',usd:Number(process.env.ZYTE_ESTIMATED_COST_USD||0.001)},timeoutMs:Number(process.env.ZYTE_TIMEOUT_MS||20000),retry:{maxAttempts:2},reversibility:'read-only'}]}}}

export async function invokeZyteCapability(cap,input,{fetchImpl=fetch}={}){
  const inputErrors=validateSchema(cap.inputSchema,input);if(inputErrors.length)throw new DomainError('invalid_capability_arguments',422,inputErrors);
  if(!zyteConfigured())throw new DomainError('zyte_credentials_not_configured',503);
  const target=safeUrl(input.url);if(target.username||target.password)throw new DomainError('target_url_credentials_forbidden',422);if(!['http:','https:'].includes(target.protocol))throw new DomainError('target_protocol_not_allowed',422);
  const endpoint=safeUrl(apiUrl());const requestedAt=new Date().toISOString(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.min(30000,Number(cap.timeoutMs)||20000));
  const payload={url:target.toString(),[input.renderBrowser?'browserHtml':'httpResponseBody']:true};
  try{const response=await fetchImpl(endpoint,{method:'POST',headers:{'content-type':'application/json','accept-encoding':'gzip, deflate',authorization:`Basic ${Buffer.from(`${process.env.ZYTE_API_KEY}:`).toString('base64')}`},body:JSON.stringify(payload),signal:controller.signal});const text=await response.text();if(Buffer.byteLength(text)>MAX_RESPONSE_BYTES)throw new DomainError('zyte_response_too_large',502);let raw;try{raw=JSON.parse(text)}catch{throw new DomainError('zyte_malformed_response',502)}if(!response.ok)throw new DomainError(`zyte_http_${response.status}`,response.status>=500?502:422,{status:response.status,type:raw?.type||null});const html=input.renderBrowser?raw.browserHtml:decodeBody(raw.httpResponseBody);if(typeof html!=='string')throw new DomainError('zyte_content_missing',502);const normalized={sourceUrl:sanitizeSourceUrl(target),observedAt:new Date().toISOString(),content:{text:extractText(html).slice(0,MAX_EXTRACTED_CHARS),title:extractTitle(html),links:extractLinks(html,target).slice(0,MAX_LINKS)},responseMetadata:{provider:'zyte',requestedAt,statusCode:Number(raw.statusCode||200),contentType:headerValue(raw.httpResponseHeaders,'content-type'),bytes:Buffer.byteLength(html),requestId:response.headers.get('request-id')||response.headers.get('x-request-id')||null,truncated:html.length>MAX_EXTRACTED_CHARS}};const errors=validateSchema(cap.outputSchema,normalized);if(errors.length)throw new DomainError('invalid_capability_output',502,errors);return{output:normalized,metadata:{provider:'zyte',sourceUrl:normalized.sourceUrl,observedAt:normalized.observedAt,responseMetadata:normalized.responseMetadata},latencyMs:Date.now()-Date.parse(requestedAt)}}catch(error){if(error?.name==='AbortError')throw new DomainError('zyte_timeout',504);throw error}finally{clearTimeout(timer)}
}

function decodeBody(value){if(typeof value!=='string')return null;try{return Buffer.from(value,'base64').toString('utf8')}catch{return null}}
function extractTitle(html){return decodeEntities(String(html).match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s+/g,' ').trim().slice(0,500)}
function extractText(html){return decodeEntities(String(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function extractLinks(html,base){const links=[];for(const match of String(html).matchAll(/<a\b[^>]*\bhref\s*=\s*["']([^"']+)["']/gi)){try{const url=new URL(match[1],base);if(['http:','https:'].includes(url.protocol)&&url.origin===base.origin&&!links.includes(url.toString()))links.push(url.toString())}catch{}if(links.length>=MAX_LINKS)break}return links}
function decodeEntities(text){return text.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
function headerValue(headers,name){const found=Array.isArray(headers)?headers.find(x=>String(x.name||x[0]).toLowerCase()===name):null;return found?String(found.value||found[1]||''):null}
function sanitizeSourceUrl(url){const safe=new URL(url);safe.username='';safe.password='';for(const key of [...safe.searchParams.keys()])if(/token|key|secret|password|signature/i.test(key))safe.searchParams.set(key,'[REDACTED]');return safe.toString()}
